### ISSUE TITLE
Add Region (Areas) filter for Campaign data in APMIS 

### ISSUE THREAD

**Issue by adekunleakerele** [xlg8/APMIS-Project#1]
Description
For all filters and dropdown options of admin org units (Areas, Regions, Districts, Communities) in the case of APMIS (Regions, Provinces, Districts and Clusters), The Region entity is not displayed in the filter for campaign data. This needs to be show as country folks want to filter campaign data by region and then export.

Steps to Reproduce
Go to https://test.afghanistan-apmis.com/sormas-ui/#!campaign/campaigndata/?campaign=WCEGBB-3ZWK7X-QQCYZU-3BAHSGCU
On the filter tab, you will notice that region filter is missing.
Expected Behavior
Region filter should be before Province filter.

Screenshots
https://user-images.githubusercontent.com/60390281/119436211-bc733200-bce9-11eb-8f8f-05fdb18566a4.jpeg
![image](https://user-images.githubusercontent.com/43553511/133838069-52cc08aa-981c-48f1-b1e4-e295b03b80ff.png)

**Comment by Iyanuu** [comment]
@ToluOlayinka @xlg8 @bnygren A bug was noticed on testing that prevents filtering with 'Region'. This is currently been worked on?

**Comment by xlg8** [comment]
@sundayAdu @Iyanuu @ToluOlayinka @bnygren @RaziaMahmodi  This only works for the dashboard. However, the region filter does not work within the campaign directory list. Province and district filters work. Please check this and revert.

**Comment by bnygren** [comment]
Reviewed in 1.0.11 
@RaziaMahmodi Please confirm cascading values are correct
