### ISSUE TITLE
Adding title for User fields

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#100]
### Problem Description

Adding title/label for User field as following:
Users Status => Active?
User Roles => User Roles
Region => Region
Province => Province
District => District

### Additional Information

https://test.afghanistan-apmis.com/sormas-ui/#!users/?region=Q57N7D-BDMZES-VC3KTH-JUYS2GGM

![12345](https://user-images.githubusercontent.com/88741672/152417095-ecda9117-8bb1-46cb-98bb-cfceba367287.JPG)

**Comment by ToluOlayinka** [comment]
@RaziaMahmodi 
Please we need more clarification on this.

**Comment by bnygren** [comment]
@ToluOlayinka @sundayAdu @RaziaMahmodi This is just labels for the dropdowns... Does this example help clarify?
![image](https://user-images.githubusercontent.com/60660864/158405516-8305b2f9-f90e-491d-ab50-2637a781d4d6.png)

**Comment by bnygren** [comment]
@ToluOlayinka @RaziaMahmodi Also note the actual screen now includes region filter now, but hopefully the above example makes sense.

**Comment by sundayAdu** [comment]
This make sense. Thank you.

**Comment by bnygren** [comment]
@RaziaMahmodi this looks complete to me, closing
