### ISSUE TITLE
Redesign Campaigns > Campaigns > Edit/New Campaign page 

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#102]
### Situation Description

more intuitive UI needed to meet needs of campaign setup; re-envision overall design and UX for this page

List of applicable forms with checkboxes suggested to enable batch-select of desired forms. Consolidated with https://github.com/xlg8/APMIS-Project/issues/89

### Feature Description

![9EF2F7E7-57C5-42BF-927E-1D1CF40EB571](https://user-images.githubusercontent.com/71328926/152684055-343498d9-5306-4752-848e-7c6e0e3ad174.jpeg)

### Possible Alternatives
![UI Issue102](https://user-images.githubusercontent.com/11197190/152687836-fcedec19-a421-43f7-927c-e8fbc6497ab7.jpg)

### Additional Information

See also https://github.com/xlg8/APMIS-Project/issues/89

**Comment by ToluOlayinka** [comment]
Proposed Interface
![UI Issue102](https://user-images.githubusercontent.com/11197190/152687722-c661652d-0e5b-46ba-a176-7a1bb2b4db46.jpg)
# #

**Comment by ToluOlayinka** [comment]
Updated a possible alternative

**Comment by bnygren** [comment]
Superseded by new UI with Vaadin upgrade. Create a new issue if further mods to that are needed.
