### ISSUE TITLE
New Dashboard UI elements for Non-campaigns (Special Interventions, PTT)

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#103]
### Situation Description

Dashboard currently shows Campaign data. There will be a need to show additional data types that are not necessarily part of a distinct campaign event: "Special Interventions" incl. PTT, Vitamin A

Dashboard UI will need tabs for Campaigns / Special Intervention 1 (e.g., PTT) / Special Intervention 2 (e.g., Vitamin A)
Within campaigns, there will still need to be subsection for each phase (pre-, intra-, and post-)

**Comment by xlg8** [comment]
![1493F281-601A-4A45-9147-0DB9142B7C45](https://user-images.githubusercontent.com/71328926/152596701-9282d97d-93d7-4370-aa85-8cf6b614b68b.jpeg)
![90E60F44-223C-423B-ABB5-AA8A00309E12](https://user-images.githubusercontent.com/71328926/152596704-c0775951-ad09-4e43-b7a7-f8a320ee04bf.jpeg)

**Comment by xlg8** [comment]
Some visual ideas
![image](https://user-images.githubusercontent.com/71328926/153632637-4ccd4b40-f5ee-4606-a915-080549a3b526.png)
![image](https://user-images.githubusercontent.com/71328926/153632684-69ceb81e-bdbd-4986-9d43-229f1d133c08.png)
![image](https://user-images.githubusercontent.com/71328926/153632772-895ab4ae-dcb3-4d3d-a478-785eaace0167.png)
@bnygren @sundayAdu

**Comment by bnygren** [comment]
@RaziaMahmodi please lead on identifying the preferred design for this. thanks

**Comment by bnygren** [comment]
@ToluOlayinka @xlg8 I don't think this is done, or even fully defined as a requirement... let's discuss, but setting to 'reviewed but not complete' for now

**Comment by ToluOlayinka** [comment]
> @ToluOlayinka @xlg8 I don't think this is done, or even fully defined as a requirement... let's discuss, but setting to 'reviewed but not complete' for now

It looks like an issue that would be ongoing for a While.
We would keep improving it as it comes.

**Comment by bnygren** [comment]
duplicate
