### ISSUE TITLE
Import/Export Storage of data entry inputs in APMIS

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#105]
### Bug Description

Currently when importing a data set into APMIS, we use the associated import template provided as .csv and transform the raw data from the specified form into the import template. After that process has been completed, we use the import feature to upload the revised template into APMIS. When you click on import, you immediately have a pop-up description which informs the user that there is an overwrite command needed or skip for the data about to be imported. Once you overwrite or skip, you get a looping effect which could stay up to 15 minutes if not stopped. The data does not import completely and even if it imports, there are some empty fields that are left blank meaning that the import was not completely successful after exporting the data that was imported. 
### Steps to Reproduce

1. Transform the raw data( ICM Supervisor House to House Checklist), into the downloaded import template
2. Import the template into APMIS by using the import feature
3. The import process is processed into an overwrite/skip forever loop until operation refreshed by user to cancel operation
### Expected Behavior

1. Transform the raw data( ICM Supervisor House to House Checklist), into the downloaded import template
2. Import the template into APMIS by using the import feature
3. The import process should be processed showing the import status bar for every single record imported. If a duplicate is found, then only then should an overwrite/skip operation begin while allowing the user to overwrite, skip or cancel operation
4. Data should have been imported at the end of operation that exported data shows the data imported
### Screenshots

[Test_IMPORT.csv](https://github.com/xlg8/APMIS-Project/files/8041490/Test_IMPORT.csv)
![image](https://user-images.githubusercontent.com/71328926/153422898-94df4cf2-4de7-4003-ba18-deec85ad5b52.png)

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by xlg8** [comment]
@sundayAdu @ToluOlayinka @bnygren @RaziaMahmodi So we tested this issue again and observed that the test data import worked successfully only if the date column is unique. This does not make any sense to restrict import when date field is a duplicate because several reports can be made on the same day. The export works as well when the all fields imported are also unique. 

Some suggestions
1. Allow date field duplication for data import and run import function on row record not field values only. It is possible for date of report, region, district, province and cluster to be the same for more than 10000 records. 
2. Make date field as timestamp up to the microsecond to avoid any chances of date duplication. 
3. Improve the duplicate-checking mechanism of the import feature to suit APMIS and not use the current SORMAS case based duplicate mechanism

**Comment by Iyanuu** [comment]
@xlg8 "yyyy-MM-dd HH:mm:ss.SSS" timestamp format will be used to improve specificity of the date field.

**Comment by bnygren** [comment]
@Iyanuu I understand. But if this is imported data, potentially historical data also, it seems like many records would simply have a date with yyyy-MM-dd 00:00:00.000 (i.e., time is always 0) since there is no timestamp (only a date). In this case I think we should drop duplicate error checking by date until a true UID or sufficeint alternate approach can be proposed. @xlg8 please comment, I may be missing something. Thanks.

**Comment by xlg8** [comment]
@Nygren, Benjamin L. ***@***.***>We can handle this in two ways. A temporary solution could be 1. If the time stamp is randomly assigned as a non null value but assigns same date but a micro second or fraction of a second uniquely to each record, we could get all historical data into the system. 2. For a more sustainable duplicate mechanism, we follow your suggestion to be very ail the import mechanism that Vitagroup put in place and ensure the sensitivity and specificity of duplicate checks is reduced for aggregate import records and create our own rules for importing data instead of using the default sormas  core rules which is mainly for case records. We can discuss further on this tomorrow
Thanks @Nygren, Benjamin L. ***@***.***>

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Iyanuu** [comment]
@bnygren @xlg8 Thanks
A good approach we are considering would be to review the present duplicate checking logic.  Currently,  the system allows for only one type of form per community on any given day. This can be improved to rather check for duplicate forms submitted by Monitors on a day in a community. 
We will need to know if there is a possibility for Monitors to submit the same type of form twice or more on a day.

Also, @abahsuccess raised issue #115 as a temporary fix.
