### ISSUE TITLE
Change Campaign-round to Campaign Phase in campaign creation list

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#106]
### Problem Description

Campaign phases have the word Round in their tab names. Please change to phases instead of round
### Proposed Change

Change Campaign-round to Campaign Phase in campaign creation list
### Additional Information

![image](https://user-images.githubusercontent.com/71328926/153656761-60595c0a-5296-4437-90db-4950f47dc88d.png)

**Comment by bnygren** [comment]
Pre-campaign seems to be corrected, but intra- and post- still show 'CAMPAIGN-ROUND FORMS' and 'CAMPAIGN-ROUND DASHBOARD'

**Comment by ToluOlayinka** [comment]
Thank you @bnygren we would adjust that  and it would be updated in the release due later today or Tomorrow

**Comment by Iyanuu** [comment]
@xlg8 @bnygren @ToluOlayinka @sundayAdu
