### ISSUE TITLE
Login window alignment, formatting on test server

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#108]
Login window appears low, with a large gap between it an the title compared with the main server. Map background is missing. 
1.0.8

**Comment by ToluOlayinka** [comment]
Login Portal Top padding has been reduced and is now in the same position as the Main server login page.
Would be in v1.0.9

**Comment by ToluOlayinka** [comment]
Issue fixed and Live and Text server are now similar in dimension and alignment aside the color difference.
@bnygren

**Comment by bnygren** [comment]
Still overlaps on default resolution settings of 1920 x 1080 with default text size (150%)

**Comment by bnygren** [comment]
Checked 1.0.11. Per discussion 2-Mar agreed to reformat without header to eliminate framing layout conflict issues in different resolutions.

**Comment by ToluOlayinka** [comment]
@xlg8 A New layout rearrangement could also fix the issue. thank you for the pointers.
![Login](https://user-images.githubusercontent.com/11197190/157123085-b97ffae4-a72c-4007-b357-80ddeaa556b9.jpg)

**Comment by bnygren** [comment]
The above looks good to me. The current view presents like this on my laptop, w/ default settings (1920x1080, 150% text), so still getting cut off. 
![image](https://user-images.githubusercontent.com/60660864/157489125-aa275543-cca0-4faa-bb99-23d0a5409bfd.png)

**Comment by ToluOlayinka** [comment]
> The above looks good to me. The current view presents like this on my laptop, w/ default settings (1920x1080, 150% text), so still getting cut off. ![image](https://user-images.githubusercontent.com/60660864/157489125-aa275543-cca0-4faa-bb99-23d0a5409bfd.png)

We are still working on this. Code didn't work as well when moved to the test server. would be fixed in next release

**Comment by bnygren** [comment]
![image](https://user-images.githubusercontent.com/60660864/159342863-b8d5e9c7-6437-4a90-a74b-eaeb0d7c02e0.png)

**Comment by bnygren** [comment]
Functional @1920x1080, 1366x768, 1280x720 on Edge. Some cutoff on bottom. Overall seems like an improved page that is less complex would make sense long term, but ok for now.
