### ISSUE TITLE
Add year filter to Campaign Directory page

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#113]
### Situation Description
Need to filter campaigns by year

### Feature Description

Add a dropdown to apply year filter, after 'Search campaign' text box
Year should be extracted from campaign start date. (It is not independent variable; i.e., user should not be able to set a year independently).

**Comment by sundayAdu** [comment]
@bnygren and @xlg8 
While looking at this issue, it seems not achievable because we are not currently collecting YEAR as a data element on the campaign. Can we go ahead and add it to the campaign? wihtout this, the year filter may not give a relaiable data.

**Comment by xlg8** [comment]
@ToluOlayinka @bnygren @sundayAdu Yes I agree. It has not been there from the very begining for campaigns. We would need to add it to the schema and also to the required tables as well as the campaign component. It would also be helpful for meaningful yearly trends over time. Please go ahead and add it to the campaign as its a main request of the stakeholders in country. Thanks

**Comment by xlg8** [comment]
@ToluOlayinka @sundayAdu Please remove the . from the year shown. For the next phase, we should also think about splitting Month as well. Thanks I will close this now.
