### ISSUE TITLE
Suspension of the Duplication mechanism on data import

### ISSUE THREAD

**Issue by abahsuccess** [xlg8/APMIS-Project#115]
### Feature Description
Currently, the system prevents the upload of duplicate data fields based on the date field.

### Problem Description
Imported data is checked for a duplicate on the date field. This prevents complete data import as there is a possibility for multiple data to be uploaded on the same day. 

### Proposed Change
The current duplicate checking mechanism should be suspended while a new duplicate check is being developed.

**Comment by bnygren** [comment]
This is done, right?

**Comment by ToluOlayinka** [comment]
@bnygren Last i check it was
