### ISSUE TITLE
Change Form Type from front end user form entry to be read-only field

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#119]
### Feature Description

Remove redundant Form Type from front end user form entry. From the backend, JSON forms already have an assigned formtype for each form and it would be redundant to allow the users select a formtype after entering the data. This happens when you have the campaign phase filters to the cascade mechanism. 
### Proposed Change

- [x] Remove existing dropdown
- [ ] Show form type (Phase category - e.g., pre-campaign) as read-only in form view @ToluOlayinka @sundayAdu 

Make field type read only showing the category of the form without allowing front end change

**Comment by bnygren** [comment]
@ToluOlayinka Let's discuss. Note sure read only is needed still, in which case issue would be closed.
