### ISSUE TITLE
Campaign statistics error on duplicate campaigns.

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#121]
### Bug Description

When you set up a duplicate campaign and try to import data, once you import the data, the campaign directory defaults back to the parent campaign that the duplicate originated from. The other error is that the campaign statistics throws an error when you click on it and the form filter does not work. 
### Steps to Reproduce

1. Open an existing campaign and duplicate it
2. Open duplicated campaign and import data, campaign list defaults back to parent campaign
3. click on campaign statistics and see error pop up. Filter by forms and see bug

### Screenshots

![image](https://user-images.githubusercontent.com/71328926/156413372-4e4e7e34-5991-4391-9396-df25b74f7199.png)
![image](https://user-images.githubusercontent.com/71328926/156413479-0520afbc-a764-4f97-8679-8526219a66a9.png)

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by sundayAdu** [comment]
We cannot reproduced this bug. also tested on test site... I will suggest we move this to close.

**Comment by bnygren** [comment]
tested, ok
