### ISSUE TITLE
Save and add new button showing in an unwanted place.

### ISSUE THREAD

**Issue by abahsuccess** [xlg8/APMIS-Project#124]
The save and add new button is showing where it is not supposed to be.
@sundayAdu @Iyanuu

**Comment by sundayAdu** [comment]
fixed with https://github.com/xlg8/APMIS-Project/commit/196cbdd6409b6834ec2d5627331a1f0ef3f6cd7c

**Comment by bnygren** [comment]
not yet available to review on TEST 1.0.12
