### ISSUE TITLE
Campaign Data and Campaign Statistics Form directory view

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#129]
### Feature Description

Currently, we have campaign data and campaign statistics default view have the same directory list which shows the list of forms, region, date, as their default pages which makes it redundant. On the campaign data, on click, filter the list by form (alphabetical order), to show form data records by attributes (Children immunized, Number of vaccinated, number of Missed children, etc.) while removing the default form view. While in Campaign statistics, retain the form view with form counts, region, province, date, etc. But let form filter remain to view aggregate form records by attributes (Children immunized, Number of vaccinated, number of Missed children, etc.)
### Problem Description

remove this view
![image](https://user-images.githubusercontent.com/71328926/158236952-b365db91-830a-48d7-b1bb-6d2155559851.png)

### Proposed Change

Filter default view by form data
![image](https://user-images.githubusercontent.com/71328926/158237158-263025e7-7a09-47f5-a42c-155a473bc158.png)

Retain campaign statistics by form view
![image](https://user-images.githubusercontent.com/71328926/158237312-7a9fec7b-6ac3-4c4e-ba8e-066d842b1af9.png)

**Comment by bnygren** [comment]
@sundayAdu @xlg8 This view page loads very slowly so this may need to be prioritized. We can discuss. Thanks.
