### ISSUE TITLE
Changing language behavior

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#132]
### Feature Description

There are 2 issues related changing language:

- [x] 1- By clicking on Language (on side menu), User Setting popup window will get open in blank page. https://test.afghanistan-apmis.com/sormas-ui/#!language
It is preferred, by clicking on language, user still stay on their current page.

- [x] 2- Save button change the language but does not close the popup win. Only Close button works for closing it. (and as result of it user will stay on blank page)

**Previous behavior of changing language which still running in main system is preferred. (Please refer to it for more clarification.)**
### Additional Information

![lang test](https://user-images.githubusercontent.com/88741672/158461470-73aecbd4-90ed-45a7-9ac0-f6d8cc7f50ff.JPG)
![main](https://user-images.githubusercontent.com/88741672/158461474-dbdbb1d7-0a29-4454-8a81-068cb22e8646.JPG)

**Comment by abahsuccess** [comment]
@RaziaMahmodi @bnygren @xlg8 

We will need Pashto and Dari translation for the "language" caption.

**Comment by xlg8** [comment]
@abahsuccess I will close this when you have added زبان to Language for Dari. Pashto is fine. It translates. Thanks
