### ISSUE TITLE
Add cluster number to population import on configuration menu

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#135]
### Feature Description

The target population on the configuration tab has an option to import the population data. RIght now, Cluster numbers are only used instead of cluster names. Import system is set to cluster name so we cannot import cluster numbers which would then provide us the target population by cluster numbers.
### Proposed Change

Please add a new column as a number field to the import template for cluster number
### Additional Information

![image](https://user-images.githubusercontent.com/71328926/161276045-cc363590-f13e-4e80-85a4-36e11cc9354a.png)

**Comment by sundayAdu** [comment]
@xlg8 @bnygren  are we to add this additional column or replace the Cluster name with No?
