### ISSUE TITLE
Campaign phase filter- Post Campaign "New Form dropdown" does not work

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#137]
### Bug Description

Campaign phase filter- Post Campaign "New Form dropdown" does not work. That phase has over 10 forms for February 2022 but when you click on new form, the list is blank. 
### Steps to Reproduce

1. Click on campaign, and select Post campaign phase from the phase filter
2. Click on new form under campaign phase Post campaign, list is empty

### Expected Behavior

List should show dropdown for the selected phase.
### Screenshots

![image](https://user-images.githubusercontent.com/71328926/161280684-4d2897af-48dc-410d-8ecd-bf8708757aa4.png)

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by sundayAdu** [comment]
We cannot reproduce this bug, we tried to add a post-campaign form, and we are able to get it listed on the new form bar

![image](https://user-images.githubusercontent.com/91499626/161380655-822bb49e-ad18-4106-bf40-bfa7693e4e24.png)

**Comment by xlg8** [comment]
@bnygren @ToluOlayinka @sundayAdu I have tested this and it works now on the test server. I will go ahead and close it. Thanks
