### ISSUE TITLE
Round filter should be included in campaign form based on form data entry

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#138]
### Bug Description

Round filter should be included in the campaign form dropdown
### Steps to Reproduce

1. Click on campaign, open any form under any campaign phase
2. Check org units above form elements, Round is not active. 

### Expected Behavior

Round should be part of the core dropdown elements
### Screenshots

![3BA33DFD-90C3-4290-8B7A-819212CC3C0C](https://user-images.githubusercontent.com/71328926/161845531-c68d3721-f402-4cec-bcf2-2a95bc242759.jpeg)

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by sundayAdu** [comment]
As we are already at the phase of preparing the software for Live server deployment, can we suggest we move this to P3?

**Comment by bnygren** [comment]
@xlg8 @RaziaMahmodi Round is part of campaign definition. As such it would be implied for each form based on selected campaign correct. Is this issue still relevant?

**Comment by abahsuccess** [comment]
We suggest this issue should be closed because the Round filter is now configured during the form definition and cannot be changed by the user during data entry.

**Comment by abahsuccess** [comment]
> We suggest this issue should be closed because the Round filter is now configured during the form definition and cannot be changed by the user during data entry.

@bnygren @RaziaMahmodi @xlg8
