### ISSUE TITLE
Enable API

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#147]
### Feature Description

Enable API endpoint URL for authenticated DB access
(i.e., via https:// post get JSON)

**Comment by xlg8** [comment]
@bnygren @ToluOlayinka This is done under API. We have tested the API with PowerBI and with R. We need Cinoteck to discuss how we can have the resulting data as a data frame which is no longer the task of the API but configuring the output from a JSON to any other resulting output. So I will suggest that we close this issue and link issue [#56](https://github.com/xlg8/APMIS-Project/issues/56) related to the API with respect to a feature requirement to pull the data via the API as a data frame or relational data with record rows and columns. Thanks

**Comment by ToluOlayinka** [comment]
> @bnygren @ToluOlayinka This is done under API. We have tested the API with PowerBI and with R. We need Cinoteck to discuss how we can have the resulting data as a data frame which is no longer the task of the API but configuring the output from a JSON to any other resulting output. So I will suggest that we close this issue and link issue [#56](https://github.com/xlg8/APMIS-Project/issues/56) related to the API with respect to a feature requirement to pull the data via the API as a data frame or relational data with record rows and columns. Thanks

Alright. I think we can link it to #56
