### ISSUE TITLE
UI - Formatting updates and typos (compiled into single issue list) 

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#158]
### System-wide
- [x] **Bold** the header labels for tabular data (e.g., 'NAME', 'REGION' below) ![image](https://user-images.githubusercontent.com/60660864/168830997-b91c0e27-e48b-4be0-817c-90f0256b4e91.png) for more clarity

### Dashboard
- [x] Dropdown label for "CAMPAIGN PHASE" should be labeled "Campaign phase" to match other dropdown formatting
- [x] Dropdown values for campaign phase dropdown should not be ALL CAPS and should be "Pre-campaign; Intra-campaign, Post-campaign" to match formatting in other dropdowns (assume this also applies in Campaigns where the phase dropdown is)
- [x] Tabs should not be formatting ALL CAPS by system --> should ideally following the text specified in JSON. As All caps it is too wide 

![image](https://user-images.githubusercontent.com/60660864/168824506-ea353b89-fbdd-4b3a-9d73-91312db6362b.png)

### Campaigns

- [x] tab formatting
![image](https://user-images.githubusercontent.com/60660864/168826260-b08e56b7-bb39-4987-b340-debb8240117a.png)
Here and elsewhere where there are 'floating tabs' like this, suggest we 1) maintain the same font size for all tabs whether selected or not, (larger of the two looks more readable and there is enough space); 2) bold the selected tab as long as the font size stays the same; 3) underline in same orange which is used elsewhere as the selected color e.g., the left menu. See GitHub actually for example
![image](https://user-images.githubusercontent.com/60660864/168827447-f1107ffe-b2ba-4d9e-8a7b-6bb6923cb142.png)
* note that in the About page tabs under guides, the font is similar size on the selected tab and it works more cleanly

![image](https://user-images.githubusercontent.com/60660864/169104585-ac20d10f-b9b9-4c3c-8581-669e09f7580e.png)

The reason for 1) is that the layout spacing changes when the whole page reloads and it is a bit jarring as the browser reloads

### Configuration

- [x] Format unit codes (e.g. DCode) as unformatted number without commas (e.g., '1234' rather than '1,234')

![image](https://user-images.githubusercontent.com/60660864/169582088-b4db6fb8-46dd-41ba-a948-60913476a2bc.png)

### About
- [x] Double colon in "APMIS Version:: 2.0.3" --> make single colon

**Comment by abahsuccess** [comment]
@Iyanuu and team can we have this delivered before the next sprint?

**Comment by bnygren** [comment]
@ToluOlayinka @RaziaMahmodi - I only see 2 of 7 checkbox items done here

**Comment by ToluOlayinka** [comment]
More Sub issues resolved please confirm
6:7 resolved
