### ISSUE TITLE
Updated dashboard feature set

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#159]
### Situation Description

Dashboard visualization for APMIS was developed using Diagram definitions compiled by High chart. The only chart elements that were enabled were COLUMN and BAR chart. We would like APMIS to upgrade from Highcharts to amcharts (https://www.amcharts.com/javascript-charts/) or similar for improved visualization 

### Feature Description

These dashboard elements should include but not limited to : 
**XY plots**

- **Column**,
- **Bar**, 
- **Scatter plots**, 
- **Line plots**,
- **Maps*
- Line & Smoothed line
- Area
- Column & Bar
- Scatter & Bubble
-** Stacked (regular or 100%)**
- **Heat-map**
- … and any combination of the above

**Percentage**

- Pie & Donut
- Nested donut
- Funnel
- Pyramid
**Geo maps**
Map chart
- Geo heat map
- Map combined with charts
- Maps is an add-on and requires separate license.

**Table**
- Rows and Columns
- Totals
- Matrix
- Row Matrix
- Column Matrix
- Row Totals
- Column Totals

### Additional Information

https://www.amcharts.com/demos/
![image](https://user-images.githubusercontent.com/71328926/168955005-f197ce31-8d07-44cb-88bf-90b4ca10581b.png)
![image](https://user-images.githubusercontent.com/71328926/168955047-f5d38277-0d76-4641-895d-b3208dd9b799.png)
![image](https://user-images.githubusercontent.com/71328926/168955089-e53275c5-49db-44d0-8f4a-afa42be9a378.png)
![image](https://user-images.githubusercontent.com/71328926/168955122-d0964a57-617c-4a89-855f-94a71d5b37ba.png)
![image](https://user-images.githubusercontent.com/71328926/168955150-d3489c5a-893c-46fb-a4db-5c1239d15d0b.png)
![image](https://user-images.githubusercontent.com/71328926/168955216-328fd48b-fd61-4cec-9bb4-3f4f7b0ce3cf.png)
![image](https://user-images.githubusercontent.com/71328926/168955235-ccca07de-fa95-4e73-85e9-815cf6735cd4.png)
![image](https://user-images.githubusercontent.com/71328926/168955279-91085c57-69c9-4e60-a8b4-7f5afee3f798.png)

**Comment by xlg8** [comment]
We would need the syntax for every chart on JSON so we can apply this. @ToluOlayinka @sundayAdu Thanks

**Comment by bnygren** [comment]
This issue is too general and comprehensive, and was basically intended to cover the initial switch to am which is done. Will close this, and further work, e.g., maps should be defined in more detail as individual issues. 
@ToluOlayinka @xlg8 @RaziaMahmodi
