### ISSUE TITLE
Dates - correct format in forms and dataset

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#168]
### Problem Description

Date fields are defined in forms for date input. But in dataset it is not shown as date, it is shown as meaningless numbers.

### Proposed Change

Date inputs should be shown in date format in dataset. 

### Additional Information

![date](https://user-images.githubusercontent.com/88741672/170440728-15f18b01-a3aa-450e-8331-2e39aa593832.png)

![visit date](https://user-images.githubusercontent.com/88741672/170440742-20828771-a551-4fcf-9d3e-01661dd6fbb8.png)

**Comment by RaziaMahmodi** [comment]
@bnygren 
@xlg8 
I am not sure if it is considered as a bug or not, but I put it as a change request.

**Comment by bnygren** [comment]
@RaziaMahmodi @xlg8 Seems like a formatting issue. Dates are not "meaningless numbers" rather they are generally stored as numbers then formatted for users' benefit (e.g., DDMMYYY).

**Comment by RaziaMahmodi** [comment]
Done.
