### ISSUE TITLE
Add PCode, DCode, CCode to Campaign Data view

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#169]
### Problem Description

Users wish to sort by DCode or PCode or CCode while viewing submitted data in **Campaigns > Campaign Data**

### Proposed Change

Add cols for PCode, DCode, CCode to Campaign Data view screen
![image](https://user-images.githubusercontent.com/60660864/172381284-dd75acfe-7070-4ae0-8279-57eb65ef42cf.png)

**Comment by sundayAdu** [comment]
@bnygren should this be added to the filter field, or replace the name of the Region, Province ...

**Comment by bnygren** [comment]
@sundayAdu I added additional description. Does this help clarify the request?
