### ISSUE TITLE
Create default vaccination campaign form definitions #1994

### ISSUE THREAD

**Issue by adekunleakerele** [xlg8/APMIS-Project#17]
Situation Description
The SIA in Afghanistan defines a set of forms used to enter data during the intra-campaign phase (see #1989).

Feature Description
Create the data schema definitions for all these forms (see #1991).
Add addtional field types needed.

Priority Forms
ICM Team monitoring checklist
ICM HH monitoring checklist
ICM Revisit household monitoring checklist
Daily HH compilation sheet

**Comment by bnygren** [comment]
forms are updated as provided
