### ISSUE TITLE
Placing a form for receiving user feedback in About page

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#171]
### Feature Description

A form for receiving and collecting user feedback and review to the system should be placed on the "About" page. This form is currently created in Google Form. And the link of this form is:
https://forms.gle/Z6DjpvXCkw3m9Sic9
The responses of this form are getting store in a Google Spreadsheet in the APMIS project folder, Google drive.
_This link should open the form in a new tab._

But still there is need for a permanent solution to get feedback from users (maybe by/in the system itself), which requires more thought and discussion.

Related: #251

**Comment by bnygren** [comment]
@ToluOlayinka After submitting feedback in the form we see this:
![image](https://user-images.githubusercontent.com/60660864/185985124-d767a0e5-6404-436d-a4cd-a026724c88a2.png)

**Comment by bnygren** [comment]
@ToluOlayinka Where does this form info go? i.e., how do we read it? Thanks. 
cc: @RaziaMahmodi

**Comment by Iyanuu** [comment]
hi @bnygren the feedback is collected in a sheet document. We will share the link for viewing all feedback with you on slack.

**Comment by bnygren** [comment]
Thanks @Iyanuu Once we have the link we can close this issue.

**Comment by bnygren** [comment]
@ToluOlayinka Submit button not doing anything now on Test and Staging. Added bug label.

**Comment by xlg8** [comment]
@ToluOlayinka @bnygren I just tested this and its still not doing anything when clicked.

**Comment by bnygren** [comment]
confirmed on staging
