### ISSUE TITLE
Allow utilization of form values for grouping in charts (e.g., campaign days)

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#172]
### Situation Description

There is a need to display data day-wise in charts. 
### Feature Description

Group by defined fields from JSON form fields. This should be separate from the current UI dropdown element that lets users select areas (e.g., provinces to group by). This grouping needs to be defined elsewhere. At present this issue is focused on using 'day of campaign'

### Additional Information

![image](https://user-images.githubusercontent.com/60660864/172698021-bacf92b9-9a71-4585-bcf8-f27235395224.png)

**Comment by xlg8** [comment]
Daywise custom tab has solved this issue. I will close this now
