### ISSUE TITLE
Close and Open a campaign

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#174]
### Feature Description

Adding the CLOSE/OPEN switch button to campaign definition. Admin will use it to close campaign which means:

- [x] Users will not be able to import and edit data anymore (in closed campaign). But campaign data will be listed, visible and reviewable. 
- [x] Closed campaign can be open by Admin.
- [x] Mobile users should only see **active open campaign**. They don't want to add data to the wrong campaign. 

- - Closed campaign will not be listed on forms headers. (this point is not applicable to the system with current features)
- - NOTE- There can be 2 open campaigns under this scenario: There can be a test campaign for training purposes that could briefly be open while a real campaign is also open. For example, some users are entering pre-campaign data into a campaign. Simultaneously, some other users are practicing data entry for intra or postcampaign data entry. See also #253 

### Possible Alternatives

![switch1](https://user-images.githubusercontent.com/88741672/173639814-210226dd-0e28-4e96-bc57-96721a1b88e6.jpg) ![Switch2](https://user-images.githubusercontent.com/88741672/173639557-99e807a7-c392-434f-a216-f005b1123bf3.jpg) ![switch3](https://user-images.githubusercontent.com/88741672/173639560-ef9fa01b-0c05-45f8-8d3e-23d43923e04b.jpg)

### Additional Information

![close](https://user-images.githubusercontent.com/88741672/173637775-e40d87c7-b836-44fe-a075-45387a5c3840.png)

![close camp](https://user-images.githubusercontent.com/88741672/173637798-6584d104-e3a9-4cd2-be28-dc48a1311470.png)

**Comment by bnygren** [comment]
@ToluOlayinka This has a number of implications for UI and backend. we will think through and discuss with you. For now it is in Roadmap.

**Comment by RaziaMahmodi** [comment]
I moved the 2 last tasks to a new issue (issue #282).

**Comment by abahsuccess** [comment]
@xlg8  @RaziaMahmodi We suggest the third task in this issue be removed as it contradicts issue #253. Hence, we suggest the issue be closed.
