### ISSUE TITLE
Testing Issues Arising From APMIS System- URGENT

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#177]
- [x]  When dashboard is viewed on different screen resolutions, the card image values show different sizes. it should not be so. 
![differSizeProbl](https://user-images.githubusercontent.com/71328926/173874002-d23aeeb8-789e-40f0-9b05-dd0f65663b7e.jpeg)
- [x] In previous chart diagrams (high chart), normally when data is missing, it should say nothing to display while still showing the chart. But in am chart, the chart disappears when  there is nothing to display leaving a gap in the dashboard
![disapearChart](https://user-images.githubusercontent.com/71328926/173874878-eaa05de5-93af-45f5-81a3-fe0dcc5ffbc5.jpeg)

- [x] Any value that has a decimal point that is called into the dashboard automatically shows a % value even when we dont want it to show.  
- [x] see example with missed children showing 100% when in the backend calculation it is showing 43. No matter what the result of the variable Total Missed CHildren, it just shows 100%. This is not supposed to be. it is not a % or 100.
![differSizeProbl](https://user-images.githubusercontent.com/71328926/173876302-9e14672c-b300-47fb-a30e-68282260e6b1.jpeg)

- [x] In the chart element, switching from percentage value to count value and vice versa has been deactivated. Please return it back for COLUMN and BAR charts
![9F6045BD-6BE6-4B34-9DC5-0FF1D24D9CDD](https://user-images.githubusercontent.com/71328926/173877724-abceb0b6-4205-4b03-ad1b-69fd3e4c6b71.jpeg)

- [x] Alot of the calculations we want to do on the dashboard needs the target population data to be able to calculate as a data element as well. Right now we cannot do that. Ability to calculate two field ids from different form ids on the campaign definition JSON 

- [x] Importing data into APMIS using CCode as the only validator is not working as the ccode in system does not always match with concatenated ccode from import (e.g. cluster number always provided, ccode not. So importing user would have to create a concatenation of "cluster number", "dcode","pcode","rcode" as a new ccode variable but import still does not work.

- [x] Day wise trend splitting Days 1-3 to day wise and day 4 within the same form id for data entry (#66)
- [x] The dropdown wrap issue is present on the dashboard and prevents users from using filters actually issue seems different in test. there is now horizontal scroll bar. but doesn't wrap (UI from CInoteck) see #205 
- [x] We need to have a hybrid view of count (%) for all APMIS charts. E.g. for normal charts, what we need is the 84(54%)

**Comment by bnygren** [comment]
@xlg8 Thanks for compiling. These various issues should probably be broken out into individual issues so they can be prioritized. We can discuss.

**Comment by xlg8** [comment]
I will close this issue now as I have confirmed individual tasks that have been completed. Thanks
