### ISSUE TITLE
Float or decimals do not show on dashboard

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#180]

**Comment by xlg8** [comment]
See form calculation problem- Calculations done based on target population and vaccinated children as an example that produces an output of a decimal or float rounds up value as a whole number instead of a float or decimal. Values with 0.96 or 0.45 outputs as zero in the calculation output. This affects dashboard output say Vaccination coverage of 0.83 or 83% is showing as 0.0 or 0.0%

**Comment by sundayAdu** [comment]
@xlg8 we need screenshot to of this issue
could this be limited to expression output or also the percentage configuration on the dasboard definition?

**Comment by xlg8** [comment]
See image. The percentages are not showing based on the output. Not on the calculated field or on the dashboard 
![image](https://user-images.githubusercontent.com/71328926/174087694-8f1fa783-2dd1-46e9-a6e0-5682b4d1e6b9.png)

**Comment by xlg8** [comment]
@sundayAdu
