### ISSUE TITLE
Campaign area unit completeness report page for administrative data

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#185]
### Situation Description

Users wish to see progress of data entry for an area (e.g., province, district, cluster). Applies specifically to administrative coverage
### Feature Description

Create a new summary page within campaigns that shows completeness by area for administrative coverage data

### Additional Information

Also related to #164 
related to #184

**Comment by bnygren** [comment]
@bnygren to build an example/template/mockup

**Comment by RaziaMahmodi** [comment]
A completeness report should be provided for each data form:
Administrative Coverage Report for pending or missed data part (formid = REV_AdminCovDataH2H_Day1_4):

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:\Users\C-Zone\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\C-Zone\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>



Region | province | district | name | clusterNumber | ccode | Admin_day1 | Admin_day2 | Admin_day3 | Admin_day4 | Message
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
East | Kunar | Shegal | Helalzo | 8 | 1306008 | 1 | 1 | 1 | 0 | No data has been   entered for these clusters on these days
East | Laghman | Alingar | Sangar South Part | 18 | 704018 | 1 | 1 | 0 | 1 | No data has been   entered for these clusters on these days
East | Laghman | Mehtarlam | Alishang | 18 | 701018 | 1 | 1 | 0 | 1 | No data has been   entered for these clusters on these days
East | Laghman | Mehtarlam | Itpaya | 13 | 701013 | 1 | 1 | 0 | 1 | No data has been   entered for these clusters on these days
East | Laghman | Mehtarlam | Qala Shiekhan | 7 | 701007 | 1 | 1 | 0 | 1 | No data has been   entered for these clusters on these days
East | Laghman | Mehtarlam | Tamerona | 37 | 701037 | 1 | 1 | 0 | 1 | No data has been   entered for these clusters on these days
East | Nangarhar | Achin | Sandaq | 10 | 617010 | 1 | 1 | 0 | 0 | No data has been   entered for these clusters on these days
East | Nangarhar | Durbaba | Gorkoh | 7 | 622007 | 1 | 0 | 1 | 1 | No data has been   entered for these clusters on these days
East | Nangarhar | Hisarak | Chartoot | 2 | 610002 | 1 | 0 | 1 | 1 | No data has been   entered for these clusters on these days
East | Nangarhar | Jalalabad | Angorbagh Gulbahar   Mena | 25 | 601025 | 1 | 0 | 1 | 1 | No data has been   entered for these clusters on these days
East | Nangarhar | Surkhrod | Char Bagh-31 | 31 | 603031 | 1 | 0 | 1 | 1 | No data has been   entered for these clusters on these days



</body>

</html>
