### ISSUE TITLE
Campaign > Campaign Data > Sort not working

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#187]
### Steps to Reproduce

1. Campaign > Campaign Data >
2. Sort by PCode, CCode or DCode
3. Scroll down and observe that records are not sorted by the column indicated

### Expected Behavior

Sort by column clicked

### Screenshots

![image](https://user-images.githubusercontent.com/60660864/175553955-0e0d7d40-f26a-4419-b831-5640a3fc3c30.png)

**Comment by xlg8** [comment]
Tested and working. I will close this now.
