### ISSUE TITLE
Ability to display Targeted Children (populationAgeGroup) as a calculatable data element on the JSON form definition or diagram JSON definition

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#195]
### Feature Description

Currently, the APMIS system uses populationAgeGroup within the **diagramseriestotal** as a default denominator when percentages are calculated on the dashboard. 
![image](https://user-images.githubusercontent.com/71328926/176213037-f550c335-9516-4aa8-9d72-9425eb5a59fe.png)

This populationAgeGroup data is pulled from the database table (populationData). This populationAgeGroup data is actually "Targeted Children". We need to be able to visualize populationAgeGroup as a whole number or use as a calculative element within the JSON form definition
![image](https://user-images.githubusercontent.com/71328926/176213205-00ce6891-44bc-40f7-84f7-2ec9ba33ead4.png)

### Problem Description

However, we are not able to use that populationAgeGroup data anywhere else on the form or dashboard. We need to be able to call the populationAgeGroup as a variable on the dashboard as sum, count or average or use within the form definition as a calculative element either as a numerator or denominator. E.g 
```
{
    "type": "number",
    "id": "VaccCov",
    "expression": "TotalChildrenVaccinated/populationAgeGroup0_4",
    "caption": "Total children vaccinated by Targeted Children",
    "styles": [
      "row"
    ]
  },
```
### Proposed Change

1. Make populationAgeGroup a calculative element within the JSON form definition for arithmetric procedures
2. Make populationAgeGroup a whole number data variable to be displayed as sum, count or average on dashboard filterable by org units

**Comment by abahsuccess** [comment]
@RaziaMahmodi @bnygren @xlg8 This is done and pushed to the test server. Please verify. 
We will update the wiki asap.

**Comment by RaziaMahmodi** [comment]
Please update the Wiki.

**Comment by bnygren** [comment]
Need to re-enable total series denominator on cards, then can close. per @xlg8

**Comment by xlg8** [comment]
@ToluOlayinka please follow up on the need to re-enable total series denominator on cards, then can close.

**Comment by xlg8** [comment]
This has been done. Waiting to apply on live server once updated. I will close this now. Thanks

**Comment by abahsuccess** [comment]
Hi @RaziaMahmodi and @bnygren, We need information why this issue is reopened.

**Comment by xlg8** [comment]
We need to wrap this issue up so we can close it. Right now the filter is still buggy. We need to have the target population and total vaccinated filter based on the active campaign @sundayAdu @ToluOlayinka

**Comment by xlg8** [comment]
I am very happy to now close this issue after a long time. It is working perfectly now. RIP Github issue #195 :) @ToluOlayinka @sundayAdu @bnygren @RaziaMahmodi
