### ISSUE TITLE
Tab form data export and calculation (Admin Data)

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#197]
### Situation Description

Regarding exporting of the data from APMIS, whenever we want to export the data from a particular province or district, the APMIS system should export all the sort data of day1-2-3 and day4 combinedly by considering cluster number. (at the moment we are exporting the data of each day separately then adjusting the data by days and cluster number)

After completing #66 , how and in what kind of structure tab data should be extracted
Related to #193 

### Additional Information

Just to mention that, Day 1, 2, 3 have the same variables. Variables for Day 4 is different from Day1-3. And grant total have different format for summation of Day1, 2, 3, 4.

Just as additional information, Country excel template:
![image](https://user-images.githubusercontent.com/88741672/177619228-925fd7b8-11f2-40c5-ac00-85a04cee9473.png)

**Comment by abahsuccess** [comment]
This issue has already been resolved with the daywise/multipart-form intervention. Forms that have consecutive days are not exported together as one. Even if it is filled partially, it will still be exported that way.

I will move that we close this after testing from the Team.

Thank you.
