### ISSUE TITLE
Logical connection and setting default value for fields:•	If the value of one field is zero, the value of one or several fields must be zero too.

### ISSUE THREAD

**Issue by sundayAdu** [xlg8/APMIS-Project#199]
• If the value of one field is zero, the value of one or several fields must be zero too.
Form Ex: District Coordinator Daily Compilation Sheet Days 1-3 H2H
Number of children Recorded Refusal = 0
Then:
Number of children found vaccinated, Refusal = 0
Number of children Vaccinated by team, Refusal = 0
Number of children Remaining Refusal = 0

**Comment by Iyanuu** [comment]
Hi, @RaziaMahmodi can you please confirm if the upgrade has been tested?

**Comment by RaziaMahmodi** [comment]
I'll close this issue as done and open another issue related setting a default value. Thanks @sundayAdu and @Iyanuu for your time.

**Comment by RaziaMahmodi** [comment]
I am reopening this issue due to users request. Also this issue discussed with @Iyanuu .
