### ISSUE TITLE
Dropdowns for filter on Dashboard page not wrapping on smaller screens

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#205]
### Problem Description

Users with smaller screens 

- cannot utilize mouse to select drop downs. Must use Alt key
- Has to scroll to the right to see the group by menu

![image](https://user-images.githubusercontent.com/60660864/179048136-3d4d17c4-4c05-43f0-be54-ef919cb8e130.png)

### Proposed Change

Wrap menus when needed. don't have them go on top of each other, eliminate scroll bar just to access the filter menu
### Possible Alternatives

Also related: For USERS screen, there is a horizontal scroll bar. This works but wrapping but be preferable there as well

**Comment by bnygren** [comment]
@RaziaMahmodi searched for existing issue but didn't see it. Please comment if this exist already. Thanks.

**Comment by RaziaMahmodi** [comment]
> @RaziaMahmodi searched for existing issue but didn't see it. Please comment if this exist already. Thanks.

@bnygren I also searched. No similar issue, except task number 9, issue #177 which you already addressed it.

**Comment by bnygren** [comment]
thanks @RaziaMahmodi

**Comment by xlg8** [comment]
Reviewed and works well. Filters show on smallest screens. We need to work on the diagrams themselves. They keep getting squashed. Another issue.
