### ISSUE TITLE
Allow users to change their own password from within APMIS

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#211]
### Situation Description

Users want to change their own passwords. Currently they can only do this via the forgot password email link method. 

### Feature Description

Have a link within the system while logged in that allows users to create a new password. 

One possible solution could be and "account" menu item on left where users can open their own user record, update their own contact details and change password as well. They would not be able to assign themselves to different area units though.  

Issue #183 : User should be able to update their own password after logging in via a link within their user profile screen. This is preferred to using the 'forgot password' route via email at the login screen.

**Comment by RaziaMahmodi** [comment]
@bnygren Issue #183 is based on country feedback which is the same with this issue. So, I will close 183. This issue has more details. Thanks.

**Comment by bnygren** [comment]
Thanks @RaziaMahmodi I missed the duplicate issue, sorry
