### ISSUE TITLE
User Data Permissions 

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#215]
Background: 

Post campaign, intra-campaign and pre-campaign phase data entry are handled by different users. There needs to be a new process for managing access to different data.

Please see complete description in a separate google doc

**Comment by xlg8** [comment]
**To add a little explanation to the need for the PCM user roles**

- Post campaign, intra-campaign and pre-campaign phases are handled by different users. There are limited view for each phases at different points in time.
-  We need to be able to allow a campaign phase user type and also like a super administrator that can handle the management and assignment of these user roles to each campaign phase
- @Ben mentioned the roles above as "Postcampaign Mobile User", "Postcampaign Coordinator"m "Postcampaign Admin". This is primarily for "Post Campaign Phase"
- The PCM data entry, data validation and data visualization should be set to pending until an admin publishes the result. WHO is fully responsible for PCM.

**Comment by bnygren** [comment]
@ToluOlayinka @Iyanuu, Great to see all the progress, but @RaziaMahmodi needs a short description of how to apply user-level permissions from the back end in order for us to review. Thanks

**Comment by RaziaMahmodi** [comment]
Thank you @Iyanuu for orienting me how to set users to WHO or EOC users. 
@ToluOlayinka I'll close this issue.
