### ISSUE TITLE
Warn user after result of a failed logical test

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#216]
### Feature Description

As a result of a failed logical test, system should either:

- [x] Prevent entry of invalid value,
- [x] Highlighting the error field with the short warning message to user. This should happen after trying to submit not all fields before the user has filled the form. 

- [ ] **Error description should appear above question or selected question with error as discussed.** 

- [x] Ability to customize Warning Message.

### Additional Information

related to #70 
Although it is a part of issue 70 but needs improvement on some details of warning users.

**Comment by bnygren** [comment]
@ToluOlayinka We removed the old allow value element of this issue and ticked the other two complete items. However, we need the highlight component to work where the user is notified which field is not filled in correctly (e.g., out of range). Per @RaziaMahmodi , Currently the user must mouseover the field with the unacceptable value to get the custom warning message. The error field should be highlighted with the error description shown next it so it is clear to the user what they need to correct.

**Comment by sundayAdu** [comment]
We are proposing to display the current error only as a pop up. As printing out singular error while clicking the field will not be possible conserdering that the onclick listener is attached to the caption.
