### ISSUE TITLE
Heavy mobile application

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#217]
### Feature Description

Heavy mobile application, need further optimization (web and Mobile app).

**Comment by bnygren** [comment]
@RaziaMahmodi @ToluOlayinka I'm not sure how we review this. The app apk is the same size ~20 MB which is reasonable for a one-time download. The main issue I think is #235 needing to be in place so user's do not perceive they need to re-download the app for updates. I am not aware of feedback that the app itself runs slow during use or complaints particularly about sync speeds (that will really be driven by network speed). I will close, then re-open if there is some relevant specific feedback to address later. Thanks.
