### ISSUE TITLE
Removing . (dot) after campaign year

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#225]
### Proposed Change

Removing . (dot) after campaign year. "2022."

### Additional Information

![Capture](https://user-images.githubusercontent.com/88741672/182914282-9ce97664-f9de-4151-b7d6-f8a4cb351d7f.png)

![Capture1](https://user-images.githubusercontent.com/88741672/182914312-0ee44023-08b6-442f-b0cd-b2d56dcd19e8.png)

**Comment by Iyanuu** [comment]
@ToluOlayinka @xlg8 This has been pushed to the test server and can be tested. There is a need to clean up campaigns before this change but any campaign created going forward will not have the "." attached to the campaign year.

**Comment by bnygren** [comment]
@ToluOlayinka @RaziaMahmodi Still has a . on test
![image](https://user-images.githubusercontent.com/60660864/186233272-b416a324-e169-44c0-956a-b37f5f46a3b8.png)
