### ISSUE TITLE
Query functionality for campaign data (indicator query module)

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#226]
### Situation Description

Submitted form data and calculations from those data are needed for indicator data summaries on the dashboard. Currently calculations are limited and built into the JSON form definition and the dashboard does not meet the project goals or provide the correct and complete data needed. Thus when new calculations are needed, JSON form definitions must be edited. Furthermore, it is difficult to reference JSON data elements in its current structure. While JSON has advantages for forms and functionality on the input side, limitations are felt when the need arises to run a standardized query from the form data. 

### Feature Description

The dashboard charts need to be informed by flexible, adaptable, queries that allow for full presentation of data within and across campaign, and are reviewable on their own. An example would be to build an data table from JSON that can be referenced by a SQL query. This will allow calculations and appropriate conversion/formatting of data for charts (e.g., ensuring integers are presented as such, denominator is correct and from the right source). Queries should be able to reference other existing queries and the administrative ("configuration") data, such that a summation could occur based on another query that extract and formats key information or performs a merge for example. Specifically defined queries should also be available for API access as deemed appropriate.

**Comment by sundayAdu** [comment]
We'll need additional information on this issue, since the current description leaves us thinking it's unachievable. Though the JSON has been regoritically improved to meet the queries specified, converting it to tables would negate the purpose of using a jsonb on the database in the first place, which is to boost flexibility in ways that are difficult to manage on a rational table.

**Comment by bnygren** [comment]
This can be moved to road map and maybe closed. part of larger discussion about how calculations outside the form can be done.
