### ISSUE TITLE
Ability to hide extra fields and do complex calculations

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#228]
### Situation Description

We have some fields in JSON forms that originally were not in the checklist. Those fields are being used for more calculations on data and analyzing for dashboard. These are considered extra fields and do not need to be shown for data entry users. 

### Feature Description

If we could have a feature similar to "readonly" feature for extra fields, we can hide them from users and not listing them in export template. 
This feature give us 2 things:
- ability to hide extra fields from users. (won't be visible for users)
- we are able to do some extra calculations within JSON forms.

**Comment by bnygren** [comment]
@ToluOlayinka @sundayAdu @Iyanuu We are happy to review but not sure how to check this. **Need the syntax described.** Thanks.

**Comment by RaziaMahmodi** [comment]
It is done. Thanks.
