### ISSUE TITLE
Ability to assign multiple clusters to Cluster Coordinator

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#238]
### Feature Description

- [ ] Ability to assign multiple clusters to Cluster Coordinator user. Cluster number (NOT cluster name) should be listed in cluster section. Cluster numbers should be listed horizontally since there can be many per district. See @RaziaMahmodi 's mockup in comments below.
(Then Cluster coordinator can be used for data entry using mobile app. Cluster Coordinator + ReST User, related to issue #243)

- [ ] Ability to assign specific form to Cluster Coordinator as well. Form categories are: ICM, PCA, PRE, REPORT, and ADMIN (admin should be added)

Mobile user can be assign to one specific form category for data entry to multiple specific clusters

Related to issue #220 and #221 

### Additional Information

![185679569-8f69a104-e2dc-4cf4-9cba-4ce49046d84b](https://user-images.githubusercontent.com/88741672/187516206-4c383bd2-1346-41ca-80a4-cc81a6088279.png)

**Comment by sundayAdu** [comment]
@RaziaMahmodi does this mean the cluster users wont be able to use the web app? or we should implement both? I will advise we implement both.

**Comment by RaziaMahmodi** [comment]
> @RaziaMahmodi does this mean the cluster users wont be able to use the web app? or we should implement both? I will advise we implement both.

@sundayAdu As your advise, cluster users are able to use both, web and mobile.

**Comment by bnygren** [comment]
@Iyanuu per @RaziaMahmodi 's comment, please display cluster number instead of name at user properties screen.

**Comment by RaziaMahmodi** [comment]
- Cluster number should be listed in cluster section. (not cluster name)
- Form categories are: ICM, PCA, PRE, REPORT, and **ADMIN** (admin should be add)
