### ISSUE TITLE
Logical check dependency on two Yes-No fields

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#240]
### Feature Description

Able or disable user for selecting one YES or NO option base on the result of another Yes/No field. (second yes/no user's answer option is depend on another yes/no field.)
Example: 

{
      "type": "number",
      "id": "childrenLivingInHouses",
      "caption": "Number of <5 years children living in the house"
    },{
      "type": "number",
      "id": "childrenVaccinatedRecall",
      "caption": "Number of <5 years children vaccinated based on recall"
    },{
      "type": "yes-no",
      "id": "poorlyCoveredArea",
      "ignoredisable":"true",
      "caption": "Poorly Covered Area: If 2 or more children are missed based on Finger Mark",
      "expression": "((childrenLivingInHouses - childrenVaccinatedRecall) >= 2) ? null : false"
    },{
      "type": "yes-no",
      "id": "missedArea",
      "caption": "Missed Area: If 2 or more houses are missed due to No team visit"
**Answer choice of this field is depends on the Yes or No answer of "poorlyCoveredArea".**
    },

Example: 
If the answer for "poorlyCoveredArea" is Yes, then user is able to select Yes or No answer choice of "missedArea".
If the answer for "poorlyCoveredArea" is No, then user is NOT able to select Yes or No answer choice of "missedArea". The answer automatically will be selected No.

**Comment by bnygren** [comment]
@ToluOlayinka @sundayAdu Per @RaziaMahmodi we need the syntax to be in the wiki then we can confirm and close. Thanks.
