### ISSUE TITLE
Mobile app URL setting options

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#248]
### Problem Description

Log in to mobile app is so tricky for users now because the URL field is hidden and they are not asked to enter the URL. In order to enter URL, users have to go to Setting and do multiple tap on "APMIS SERVER VERSION 3.1.1".

### Proposed Change

It would be great: (preferred solution)
Still keep the URL field hidden. But the link should be set to "https://afghanistan-apmis.com/sormas-rest/" by default.

### Possible Alternatives

Or: (not preferred solution)
If setting the URL by default is not possible, then like in previous version, URL should be asked from users at the beginning of log in.

**Comment by sundayAdu** [comment]
@RaziaMahmodi This is how the last apk that came out usually works. We just tried it out again, and it still works. Can we move this to close?

**Comment by bnygren** [comment]
worked for me on a fresh install without entering a URL
