### ISSUE TITLE
Mobile app does not default to last used campaign

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#253]
**The app should default to last used/selected campaign in the app.**

After closing and opening the mobile app, the selected campaign is not remembered from the last session. Normally there should be one active campaign but it is possible there may be more than one sometime. In this case to avoid user confusion, the app should default to the last used campaign.  

NOTE- There can be 2 open campaigns under a scenario: There can be a test campaign for training purposes that could briefly be open while a real campaign is also open. For example, some users are entering pre-campaign data into a campaign. Simultaneously, some other users are practicing data entry for intra or postcampaign data entry. See also #174 

Related: #284

**Comment by bnygren** [comment]
App chooses the most recent campaign at new each session in the mobile. testing on Staging and Live in 2 devices

**Comment by bnygren** [comment]
@sundayAdu @RaziaMahmodi @xlg8 Cannot seem to get this to work. Tested by selecting a campaign then closing app, reopening app and the default campaign is always July. Tried creating a new campaign on staging (TEST June) then entering a record, closing the app, reopening, entering PIN, then campaign selected is back to July. Others please test and comment. Thanks.

**Comment by sundayAdu** [comment]
@RaziaMahmodi we need to select one of this intervention. Should we make the app default to last used campaign? or the active campaign?

**Comment by bnygren** [comment]
@sundayAdu The app should default to last used campaign. The request is just to stay on whatever the last campaign the app user selected. This is not currently happening. Thanks.
