### ISSUE TITLE
Campaign stats view missing region col, grouping does not make sense

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#255]
Region col missing. Cannot interpret the table. 
See also #166

Default - has repeated rows:
![Image](https://user-images.githubusercontent.com/60660864/189730199-eccd45c9-3435-47fa-bae9-9cbb27ecf6cc.png)

By region - no region listed
![Image](https://user-images.githubusercontent.com/60660864/189730548-0545d079-0493-41bf-8a39-e915b4181369.png)

**Comment by bnygren** [comment]
Stats tab is now missing altogether so this may need to be revised. Page loads faster now.

**Comment by xlg8** [comment]
@bnygren Can this issue be closed and a new issue be created for what you need revised? Page loads faster. I think we will still need to create an issue for an aggregate system for tracking counts of data and expand the statistics element using a pivot system.

**Comment by bnygren** [comment]
@xlg8 closed as won't fix
