### ISSUE TITLE
Daywise form in mobile app is showing as grand total

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#256]
### Bug Description

Daywise tab form in mobile app is showing all day1,2,3,4 as grand total.

### Steps to Reproduce

1.
2.

### Screenshots

![1](https://user-images.githubusercontent.com/88741672/189769409-62d8f4ac-a466-4527-aac0-a05671a70dc5.jpg)![2](https://user-images.githubusercontent.com/88741672/189769420-18b370b4-4d42-4d1f-a1ea-b9c7341f65f5.jpg)
![3](https://user-images.githubusercontent.com/88741672/189769427-7907068f-49e5-47dc-9195-5f75e4a3b1c6.jpg)![4](https://user-images.githubusercontent.com/88741672/189769433-874e4e0f-c4a6-4a29-b3cd-f5fe757d0130.jpg)

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by bnygren** [comment]
tested as not working by @RaziaMahmodi

**Comment by xlg8** [comment]
@ToluOlayinka I just tested this now and its still not working even though it was put in the review section for us to review. Do we need to update the app? was there a new apk with the fix? If so, I had expected my app to trigger an update with the new fixes. Please advise. 

Thanks
