### ISSUE TITLE
Form list should be by campaign phase and alphabet

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#26]
List of forms is not in order. 

### Feature Description

It is better to have an ordered list of forms. This order can be based on campaign category and then alphabetically.

### Problem Description

Finding a form is difficult.
It is not user friendly.

### Proposed Change

- [x] Alphabetical sort.
- [x] Also, to be easier to read, from list should be left-aligned and standard-case i.e., not capitalized (which takes up more room). 

Prior to this new form lists are filtered by a dropdown after campaign that selects phase (pre-, intra-, post-) See #46 

### Additional Information

![Form List](https://user-images.githubusercontent.com/88741672/134547953-e4cd1abe-d758-43fb-93df-8521a2351e8d.PNG)

**Comment by bnygren** [comment]
list is alphabetical but not yet categorized by phase. Relates to https://github.com/xlg8/APMIS-Project/issues/46

**Comment by xlg8** [comment]
@ToluOlayinka Pending #46

**Comment by bnygren** [comment]
@RaziaMahmodi This seems complete. Phase-wise filter should be covered within #46. Updated comment there to eliminate as dependency here.
