### ISSUE TITLE
Uploading new set of population data error

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#260]
### Bug Description

![image](https://user-images.githubusercontent.com/71328926/191344344-9f99addb-7931-46bd-8d78-76f286b07815.png)

### Steps to Reproduce

1.
2.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by xlg8** [comment]
@bnygren @RaziaMahmodi I just tested this on staging server and its working now. Some points to note. 
1. Please remove any column that is null
2. Enter the population under under 4_total and remove cluster code and other variables
3. Save and import new populated template
@sundayAdu Please update live so we can do same on it. @bnygren Can we close this issue?
[sormas_import_population_data_template2222.csv](https://github.com/xlg8/APMIS-Project/files/9955917/sormas_import_population_data_template2222.csv)

**Comment by RaziaMahmodi** [comment]
Population is updated. Thanks
