### ISSUE TITLE
Refine UI to edit list items

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#27]
### Feature Description

As of now, clicking on campaigns/users/configuration opens a list. Behavior to open list item needs refinement.

### Problem Description

List presents with rows. To edit a row item, user can double click a field or click single on the "edit" button. There is no view option. The edit button is redundant, and uses col space. There is no mouseover (hover) cue elsewhere in the row to indicate the row item can be opened. Double clicking on a field opens the row item but also highlights the word.

### Proposed Change

Remove edit col, add mouseover cue, row bg change

- [ ] Remove edit icon/col
- [ ] Single click to open row item
- [x] font text should not become bold on mouseover. This makes it harder to read and can cause '...' to appear when hovering. Just change the row bg highlight and this is sufficient

### Additional Information

![image](https://user-images.githubusercontent.com/60660864/134579813-b37c4cde-03af-47bf-a8f2-a444988a8748.png)

**Comment by bnygren** [comment]
This issue is a priority to finish as it is system-wide and affects user testing/understanding of basic navigation behavior.

**Comment by ToluOlayinka** [comment]
@bnygren

**Comment by bnygren** [comment]
Still needs to be reviewed. Checkbox items in issue still pending in 1.0.9 (e.g., list view for users, campaign data not updated yet). Can review at next update to close.

**Comment by bnygren** [comment]
@ToluOlayinka Only seems to be working in Campaigns still. Have to double click elsewhere. Config and User still have the edit col.

**Comment by bnygren** [comment]
Checked 1.0.11. Still pending the description in **Proposed Change** in the issue description and consistent single click behavior in list views.

**Comment by bnygren** [comment]
Checked:
Campaigns/Campaign Data-- Single click Not working
Campaigns/Campaign Stats-- There is no click behavior expected so row should not highlight on mouseover
Campaigns/Campaigns-- Single click works correctly
Users-- Single click works correctly
All menus-- bolding on mouseover not necessary, causing some of formatting issues; 
See checkboxes

**Comment by ToluOlayinka** [comment]
Well noted. would be worked on

**Comment by sundayAdu** [comment]
Checked:
Campaigns/Campaign Data-- Single click Not working **_fixed with https://github.com/xlg8/APMIS-Project/commit/6556a88e2ffea30307f668f106ed6a199d5abd5b_**

Campaigns/Campaign Stats-- There is no click behavior expected so row should not highlight on mouseover
_as this is connected to other grid mechanism and UI, it will be tricky to get this done without redesigning the entire grid serving the Statistic Module_

All menus-- bolding on mouseover not necessary, causing some of formatting issues;
See checkboxes in issue description
**_we may need more information on this behaviour as we cannot reproduce this on the test server and dev server_**

**Comment by bnygren** [comment]
Edit icon still appears in config screen in 1.0.12. (Unchecked task in issue description)
![image](https://user-images.githubusercontent.com/60660864/158185508-983de843-69d1-4404-a6d5-158b7796da29.png)

**Comment by bnygren** [comment]
Double click required to open config row

**Comment by bnygren** [comment]
@ToluOlayinka @RaziaMahmodi Confirmed, checked off task 3 (not bold on highlight)
