### ISSUE TITLE
New form button does not show any forms in dropdown

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#271]
This seems fixed in Live. In staging there are no forms. 
Staging:
![Image](https://user-images.githubusercontent.com/60660864/193889785-8a0cd443-2655-4115-9ea6-0ef7cd7510ee.png)

Live: **dropdown menu opens but nothing happens when we click on form.** 
![Image](https://user-images.githubusercontent.com/60660864/193890499-004a7144-0460-44ec-b2ff-946c730f8bbe.png)

**Comment by RaziaMahmodi** [comment]
This issue is fixed on Live server. Thanks.

**Comment by bnygren** [comment]
Per discussion our understanding is that there was a hotfix to Live and we are pending an update to Staging with a more comprehensive fix. Once that it is available on Staging, we will review and close.

**Comment by bnygren** [comment]
@sundayAdu @RaziaMahmodi -- I am testing to close this, but In Staging, I only see forms available for the campaign July SNID 2022 in pre- and post-. There are no values in the new form dropdown for intra, but forms are assigned to intra for this campaign when checking the campaign definition. Same for May. Thanks.
