### ISSUE TITLE
Delay on resulting a calculation (form)

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#281]
If a calculation formula is set on a field. As long as the user has not gone to the last field (entering data till the end of the form), the calculation result is not calculated. The result of the calculation is determined when the user has entered data to the last field of the form.

Feedback from Users: "The application is counting the first digits of refusal vaccinated but not all the digits, while bringing curser down to the number of AFP cases then it is calculated correctly."

**Comment by bnygren** [comment]
Dev team to investigate ways to improve this

**Comment by RaziaMahmodi** [comment]
As dev team mentioned delay on calculation is a part of form logical check but we need to discuss on this issue to find a more convenient solution for users.

**Comment by sundayAdu** [comment]
@RaziaMahmodi can you please double check this issue? Its working the way it should on our side and tested on staging. Thank you.

**Comment by RaziaMahmodi** [comment]
> @RaziaMahmodi can you please double check this issue? Its working the way it should on our side and tested on staging. Thank you.

Hi. I tested this. It is working as it was before. not any change or refinement about it.
