### ISSUE TITLE
New features to Open/Close Campaign button

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#282]
- [x]  Ability of campaign (forms) get closed based on a set data entry deadline. (expiry_day_capaign)

- [ ]  Users get a notification about a campaign got closed. (based on the deadline of the data entry)
related to https://github.com/xlg8/APMIS-Project/issues/359 ,
https://github.com/xlg8/APMIS-Project/issues/360

Data entry deadline:

-FLW Operation Kit - End of the campaign = day 4 of campaign
-Training Monitoring - Day 1 of campaign
-Admin Coverage - 3 days after campaign
-ICM - 3 days after campaign
-Out of house FM survey - 3 days after campaign
-LQAS - 7 days after campaign
-PCM - 7 days after campaign

-Validation of PCM & LQAS - 10 days after campaign
-Investigation report on LQAS failed LOTs - 10 days after campaign
-SIA service providers - Day 2 of campaign

**Comment by abahsuccess** [comment]
@xlg8  @RaziaMahmodi as we are not identifying each form by this type of given deadlines, i.e SIA, ICM e.t.c. The deadline logic would be unreliable
Furthermore, can you clarify if this confirms that a campaign closure is now based on form and not campaign?

**Comment by bnygren** [comment]
@abahsuccess thanks for your comments and insight. This issue will need more description and probably some discussion to address these issues. I think it can still be regarded as a new issue and it hasn't been actually assigned to anyone on the dev side yet. But let's discuss to make sure there is a reasonable way forward.
