### ISSUE TITLE
Renaming Sync buttons in mobile app

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#289]
Renaming Sync buttons in mobile app:
Re-Synchronize data = Re-Synchronize System Setting
Sync = Submit Data 
- Remove the refresh icon and add upload icon
![Image](https://user-images.githubusercontent.com/88741672/197238497-3c7119ca-11e0-4b2c-9846-ddd86a90176e.png)

![Image](https://user-images.githubusercontent.com/88741672/197224817-5acd0048-c707-40a4-b671-09686e7de326.jpg) ![Image](https://user-images.githubusercontent.com/88741672/197224841-b7a9ba0a-ea15-443c-a138-d80707eaa833.jpg)

**Comment by RaziaMahmodi** [comment]
@ToluOlayinka I am reopening this issue because in new update those buttons renamed back to their previous name.

**Comment by RaziaMahmodi** [comment]
Hi @ToluOlayinka in mobile app version 1.0.19 the "Re-Synchronize System Setting" renamed back to "Re-Synchronize data".

**Comment by bnygren** [comment]
Hi @ToluOlayinka However, my app looks like this:


![Image](https://user-images.githubusercontent.com/60660864/206734529-dc907929-ecc9-44ac-ba31-22040f0a4e0a.png)

**Comment by bnygren** [comment]
@RaziaMahmodi My app says "RE-SYNC SETTINGS" now (middle button). "Submit Data" dropdown looks correct as well. Can this be closed?
