### ISSUE TITLE
All SORMAS related roles shown on the users module should be taken out of the APMIS and the relevant roles renamed #3664

### ISSUE THREAD

**Issue by adekunleakerele** [xlg8/APMIS-Project#3]
Feature Description
![image](https://user-images.githubusercontent.com/43553511/133838629-3321e382-8125-4d62-9120-d93fead7b51c.png)

Problem Description
Right now under users, you have so many user roles that are not related to APMIS users. This confuses the admin users to have so many user roles to select from not related to the user roles that he needs to set up.

Proposed Change
Remove SORMAS related users and have only the following for APMIS:
Hub User (no ability to change or add any data. Only readonly view but allowed to export, manipulate data and can see multiple countries)
WHO User (no ability to change or add any data. Only readonly view but allowed to export, manipulate data)
UNICEF User (no ability to change or add any data. Only readonly view but allowed to export, manipulate data)
NEOC Admin (Read, Write, Execute)
NEOC user (no ability to change or add any data. Only readonly view but allowed to export, manipulate data)
National Supervisor (RWE)
National Observer (R)
Regional Supervisor(RWE)
Regional Observer (R)
Provincial Supervisor(RWE)
District Supervisor(RWE)
Cluster Supervisor(RWE)

Possible Alternatives
Additional Information

**Comment by cassandraSMART** [comment]
fixed
