### ISSUE TITLE
Improve session timeout behavior

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#30]
### Feature Description

Auto--logout user after a configurable period of time. 

### Problem Description

Currently if a user session times out, and returns to the browser window, animation spins endlessly (see screenshot in addl info). Clicking on "click here" has no effect while the animation spins (it does work if the animation is not there), but ESC works. 

### Proposed Change

Popup or page to inform user that session has timed out --> return to main login page. 

### Additional Information

Tested in Windows/Edge
![image](https://user-images.githubusercontent.com/60660864/135126771-e32391ae-41cd-4aa1-ac6a-de21258dc145.png)
![image](https://user-images.githubusercontent.com/60660864/151251118-8b0ec41f-b23a-402e-b596-f2b8dce62b12.png)

(and Android)
![Screenshot_20220124-162639](https://user-images.githubusercontent.com/60660864/150988504-683075bd-acd4-4a13-9be1-74b10d6f69a8.png)

**Comment by ToluOlayinka** [comment]
Thanks, @bnygren this is necessarily not a bug but more of an Improvement. but we worked out some UI designs please check them out and let me know.

1. Pop up Design Centralized
![SessExpire pop-up_Cent](https://user-images.githubusercontent.com/11197190/155220199-83538acc-c1f6-4265-955e-3885d819a493.jpg)

2. Pop-up Design Top fixed. (Looking at those that might need to take not of unsaved data before refreshing. (Opacity of the page overlay would be reduced compared to the design to ensure it is a bit Visible)
![SessExpire pop-up_Cent_YIcon](https://user-images.githubusercontent.com/11197190/155220171-c208860b-c0f9-4c74-9c01-f1991245f4aa.jpg)

3. Pop up Design Centralized with an Icon
![SessExpire pop-up_Top](https://user-images.githubusercontent.com/11197190/155220182-187028a0-f7d8-4fdf-b3b1-7bbb599a38ca.jpg)

**Comment by bnygren** [comment]
Thanks, a popup is appropriate. Agreed, if the current behavior is normal for SORMAS this is improvement. Updated labels.

**Comment by bnygren** [comment]
@ToluOlayinka @sundayAdu Using Staging, my session does not time out after 4 hours with no interaction (using Edge). Please advise. Can others confirm this works? @xlg8 @RaziaMahmodi
