### ISSUE TITLE
Selected Yes-No values using mobile app won't be showing in system data rows

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#302]
Yes-No answers that users enter using mobile app won't be showing in system data rows.

Mobile app data with Yes-No answers:

![Image](https://user-images.githubusercontent.com/88741672/202273618-b87ca250-089b-4f36-b99e-b56f2f8bab90.png) ![Image](https://user-images.githubusercontent.com/88741672/202273626-4e07fef7-22da-436e-92d2-b1c0a40abd40.png)

Data row in system which Yes-No answers are not selected:
![Image](https://user-images.githubusercontent.com/88741672/202272226-b318845a-3232-43b8-a2e6-bdccd291d410.png)

**Comment by RaziaMahmodi** [comment]
Hi @ToluOlayinka , 21 of Nov is the start of campaign and mobile data entry. Could dev team do a hot fix for this issue?

**Comment by ToluOlayinka** [comment]
Yes. We would push a hot fix for this.
