### ISSUE TITLE
User is able to submit data even with logical check error

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#313]
Mobile app version 1.0.19:
1- User is able to enter invalid data by tap on the thick mark twice in app. 
2- User is not able to open that data row with logical error in it to edit in app.
3- When user try to open that data row in app by tapping, app will restart.
4- Fields with invalid data will be shown in system with no values when viewing in browser.

**Comment by sundayAdu** [comment]
Hi @RaziaMahmodi can you confirm if this still persist in 1.0.20? We cannot reproduce this error. Thank you

**Comment by abahsuccess** [comment]
@RaziaMahmodi , We cannot reproduce this error on our end. Can you give more information?
