### ISSUE TITLE
Applying filter prior to selecting campaign causes app crash

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#321]
**Description of Problem**
When a user logs into the mobile app and enters the pin to authenticate, the default state of the campaign directory list is null (no campaign selected), if the user does not select a default campaign before applying filter, the system generate a null excerption loop which crashes the app and does not allow any type of synchronization operations

**Recommended steps of action**
1. Create a default campaign as active and allow user to be able to change default selection to any other campaign desired
2. When the admin creates a new campaign, all mobile apps should default to the new campaign set to "active". 
3. Probably a pop up warning when a user clicks on "apply filter" if no campaign is selected

**Comment by xlg8** [comment]
Description of Problem
When a user logs into the mobile app and enters the pin to authenticate, the default state of the campaign directory list is null (no campaign selected), if the user does not select a default campaign before applying filter, the system generate a null excerption loop which crashes the app and does not allow any type of synchronization operations

Recommended steps of action

Create a default campaign as active and allow user to be able to change default selection to any other campaign desired
When the admin creates a new campaign, all mobile apps should default to the new campaign set to "active".
Probably a pop up warning when a user clicks on "apply filter" if no campaign is selected
