### ISSUE TITLE
Data of daywise form

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#328]
Once the data has entered in DC compilation from and submit it after checking the same data it showing only formulated data losing other information.

DCs (mobile users) cant save data of day2 and as well as for day3. Also when they back to day1, data in the system is cleaned. If they try to submit data of day3, they should start from day1 to day3. They can't save and submit single day.

![Image](https://user-images.githubusercontent.com/88741672/214303942-d55184a0-be7c-4956-b48d-e3944097854f.jpg)

**Comment by bnygren** [comment]
@RaziaMahmodi This seems like a bug. Should that label be added?
