### ISSUE TITLE
Table view column heading formats

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#329]
Column headers can be difficult to read when long or the table has many columns. To improve:

- [ ] Add a hover/mouseover which displays the full variable label when mouse pointer is over column heading
- [x] Format the column headings into standard case (i.e., "Number of children" not "NUMBER OF CHILDREN"). This will improve readability since ALL CAPS is much wider for the same amount of info.  

This can be covered as part of the UI upgrade #202

**Comment by RaziaMahmodi** [comment]
Please add a hover/mouseover which displays the full variable label when mouse pointer is over column heading too. Right now it is working on data row.

**Comment by DevSeg** [comment]
Hi @RaziaMahmodi just to add to the solution to this issue: The column description(s) are populated from the JSON form(s) and as a result, are added dynamically to the grid to display the data in them.

Hence the need to use the “Apply Filter” (Button) when filtering a particular form.

This would be a temporary fix, while we explore new ways to implement this feature.
