### ISSUE TITLE
Day 4 Revisit Admin District Coordinator Daywise Entry Buffer Lag and page crash

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#339]
### Bug Description

When you enter data into day 1 to day 3 and save, everything is ok. However, when you start to enter data into day 4, and get to the last field (AFP cases), the system starts to buffer forever and  the page crashes. 
### Steps to Reproduce

1. Open Day wise form and fill in data for day 1 to day 3
2. Fill out day 4 and try to save, buffer takes over the screen until page failure

### Expected Behavior

All pages should be able to save successfully. 
### Screenshots

![image](https://user-images.githubusercontent.com/71328926/218781226-7c88f45f-4365-4f56-a182-423d91053f04.png)

![Image](https://user-images.githubusercontent.com/71328926/218782355-b333dc38-5ddb-4455-b9bf-f8eed3e2d509.png)

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by sundayAdu** [comment]
This is not a bug, but rather miscalculation on the json form.
