### ISSUE TITLE
Specify the campaign status being "Closed" or "Open"

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#341]
Showing the campaign status next to the name of campaign in campaign list.

![Image](https://user-images.githubusercontent.com/88741672/219098156-4803c1b9-a554-48d6-8cae-5a201c9d9c93.png)

**Comment by naveeddil** [comment]
Dear Razia, As discussed today so there should be a further breakdown of Closing/ Opening (cut-off dates) for Pre, Intra and Post campaign activities so instead of opening the whole campaign the Admin should be able to open specific activity to one region or more regions
