### ISSUE TITLE
Sorting campaigns by start date

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#342]
Default setting for sorting campaigns should be by start date.

![Image](https://user-images.githubusercontent.com/88741672/219098824-45bc4da1-ac27-4dff-9d4b-60ca6db13465.png)

**Comment by RaziaMahmodi** [comment]
Not available on Live server.

**Comment by ToluOlayinka** [comment]
A push would be made to the LIVE server.
This is however available on the New system

**Comment by danieltomabba** [comment]
@RaziaMahmodi @ToluOlayinka This works on the live server, staging and new UI. I will go ahead to move it to done.

**Comment by RaziaMahmodi** [comment]
Campaigns get sorted by date modified, not by Start Date.
