### ISSUE TITLE
Allow for District-level data collection

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#348]
Currently all data (records) collected feature the same header fields which are all required (form date, Region, Province, District, Cluster). However, not all data apply to cluster level. Operation kit, FMS, Training Monitoring data do not have a cluster value for each record, but rather each record is associated with a district. 

District level forms need a means to have cluster not be a captured or required field. Ideally, when a form definition is created, there could be code in the JSON form (not visible to user) that defines the required "header" fields. E.g., a form designer could specify that District level forms only require an entry for District. The field for cluster would be disabled or invisible. 

Currently District level forms require Cluster entry so this means there have to be inaccurate/junk values entered for cluster so that the data can be entered.

**Comment by RaziaMahmodi** [comment]
Not available on Live server.

**Comment by bnygren** [comment]
Confirmed still not available after 28 June Live server update.

**Comment by ToluOlayinka** [comment]
@abahsuccess Please can we test this out and make a Hot cde push if not on Live server

**Comment by RaziaMahmodi** [comment]
This feature is available on Live server. Thanks.
