### ISSUE TITLE
Map component display on the dashboard (e.g.,missed children, inaccessibility, microplanning maps) for geo mapping )

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#35]
### Situation Description

Mapping dashboard display are very important for the APMIS project. We would like to be able to filter dashboard elements by displaying maps (E.g Modality, Campaign phase, Missed children, Reasons for missed children, etc.)

### Feature Description

We need to define what mechanism and component to implement on the dashboard for mapping display. We might also need to include this in the overall overhaul of the existing dashboard.
### Additional Information

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/71328926/156407034-a15f1cec-0478-4e22-a908-d25c09fe63d1.png)

**Comment by xlg8** [comment]
Related to #34

**Comment by bnygren** [comment]
This can be closed due since basic mapping functionality is done in APMIS and complex mapping will fall within the capabilities or R Shiny
