### ISSUE TITLE
Allow for a flexible screen resolution display on mobile, web or tablet screens with automatic adjustments with scroll bars where needed and responsive

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#36]
### Situation Description

When you view APMIS on a mobile device or tablet, you have some level of responsiveness but you still have overlap of menu bars and charts on the mobile screen and tablets
### Feature Description

We would like to have a situation where the APMIS system is responsive to automatic adjustments with scroll bars or menu bars where needed. Especially on tablets and mobile devices. The current framework only supports web browser view efficiently. This should change

needs evaluation of support for
- [ ] 1366x768 
- [ ] 1280×720
until there is info to state more specifically the use cases

### Additional Information

https://gbksoft.com/blog/common-screen-sizes-for-responsive-web-design/
https://gs.statcounter.com/screen-resolution-stats

![image](https://user-images.githubusercontent.com/60660864/151015210-f26fb400-71ac-434a-bef7-5aa294c35f56.png)

**Comment by bnygren** [comment]
Main issue seems horizontal at <=1440x900:  Dashboard > anything to the right of 'group by' control gets cutoff and there is no horizontal scrollbar.
@ 1152x864 / 1024x768 the left menu gets condensed to icons to save horizontal space. Maybe if the header in Dashboard wraps it is useable. Tested in Win 10/Edge

**Comment by bnygren** [comment]
@ToluOlayinka @RaziaMahmodi @xlg8 it seems like dummy button to the right on the Dashboard page is causing the issue still. otherwise, seems to work ok at different resolutions.

**Comment by bnygren** [comment]
May be dependent on https://github.com/xlg8/APMIS-Project/issues/46 . Thanks

**Comment by bnygren** [comment]
horizontal scroll confirmed on dashboard page at low res
