### ISSUE TITLE
Create wiki for server set up, database and system configuration documentation 

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#367]
Backend APMIS admin users utilize the pgAdmin, PostgreSQL and Putty to access the JSON form and diagram definitions to edit, update and configure the forms and dashboard. From time to time, some new admin users would need to be equipped to manage the APMIS backend system. We do not want to always reach out to the Developers to set that up because their time is precious and they can use it to concentrate on core developments. 

Hence, we request that CinoTeck creates a wiki documentation for how to set up the APMIS Server on a local test machine. We need a detailed step by step description on the wiki (https://github.com/xlg8/APMIS-Project/wiki)

The set up script should contain how to set up the PostgreSQL, Putty and Pgadmin or DBeaver for a windows or MAC machine on a test server

The set up script should also include the required port numbers (5432) and ip addresses for the staging server (123.345.345). The set up script should also contain all the default user and password credentials for demo systems. And a support email or phone number to reach out if any issues are encountered.

**Comment by bnygren** [comment]
@xlg8 these two items are not related, please create one issue for each topic with more detail

**Comment by DevSeg** [comment]
https://github.com/xlg8/APMIS-Project/wiki/APMIS-Server-Set-up,-Database-and-System-Configuration-Documentation
