### ISSUE TITLE
Allow users to reset passwords

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#38]
**Situation Description**
During server setup, server administrators can configure SORMAS to generate a number of default users that are useful for testing and development purposes. However, these users also have default passwords and thus are a potential security breach, especially if administrators forget to disable these users on production systems.

Default user generation is turned off by default, but there's still a mandatory admin user with a standard password generated.

**Feature Description**
The new feature should present a prompt at login to any of the standard users using their standard password (as is defined in StartupShutdownService:createDefaultUsers) to change their password. The password changing logic can be the same as when editing a user from the user directory.

An implementation of this: https://github.com/hzi-braunschweig/SORMAS-Project/pull/4875

What does this PR do?
This PR fixes Prompt default users to change their password on login #4690.
It provides a new feature to present a prompt at login to any of the standard users with their standard password (as defined in StartupShutdownService:createDefaultUsers) to change their password.
If we have an elevated user capable of editing other users, this user can change the standard password of other standard users as well. The new passwords can be exported as CSV.
The attached screencast demonstrates this new feature:
sormas-4690
![462E402F-7A2E-47C0-B49D-3407E6F68C55](https://user-images.githubusercontent.com/71328926/135772785-3e0044fe-23c0-4e43-81a0-90963192e7b2.jpeg)

We are happy to receive feedback from your side!

Thanks to @Snorzze for providing the unit tests!

**Comment by sundayAdu** [comment]
This seem to be the normal behaviour of the system right now. 
Can we have more information on the actual need for this?
@xlg8  Thank you.

**Comment by xlg8** [comment]
@sundayAdu Do we have this feature active now?

**Comment by xlg8** [comment]
@Iyanuu @bnygren @RaziaMahmodi @sundayAdu @ToluOlayinka We tested the request for new password, we didnt get any emails based on request. We need a verification page or popup to inform user that if the email exist in the system, you would receive a verification email to change your password. Also please check what email gateway was set up for the email notification because it does not work.

**Comment by bnygren** [comment]
observed 
![image](https://user-images.githubusercontent.com/60660864/157316981-6106c411-d166-46c2-81bf-1de272a88650.png)

**Comment by ToluOlayinka** [comment]
looks like the pop-up code for forgot password. Noted and would be fixed as well as the New login page in next relaease

**Comment by bnygren** [comment]
@ToluOlayinka Per discussion hover over 'Forgot your password' would best have the mouseover hand icon
![image](https://user-images.githubusercontent.com/60660864/158590238-721989a7-4a1a-43c9-b422-3cd70bfca2bb.png)

**Comment by ToluOlayinka** [comment]
@bnygren
This is noted and would push it to the development team. @Iyanuu do take note

**Comment by bnygren** [comment]
@ToluOlayinka @xlg8 I see the review label but nothing happens when I click on 'Forgot your password?'. No hand icon on hover, no popup. Should this be reviewed yet?

**Comment by ToluOlayinka** [comment]
> @ToluOlayinka @xlg8 I see the review label but nothing happens when I click on 'Forgot your password?'. No hand icon on hover, no popup. Should this be reviewed yet?

The issue was worked on and tested. Following up with the Dev team to check if the code broke.

**Comment by ToluOlayinka** [comment]
> We have diagnosed the issue, we are at this roadblock... https://www.linode.com/blog/linode/a-new-policy-to-help-fight-spam/
> 
> We are currently working with Linoide team to get this resolved as soon as possible.
> 
> Thank you.

We have been given a GO from Linode but just for the main server. This Issue would reflect in the Main server when updated. I'll move it to Done.
