### ISSUE TITLE
Add a dropdown admin level for “cluster” (currently the lowest level displayed is district)

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#394]
The APMIS system has 4 admin levels (Region, Province, District and Cluster). The dashboard only displays charts to district level. While the APMIS form directory displays form data to cluster level. 
![image](https://user-images.githubusercontent.com/71328926/229869688-0dd4f60a-8df8-499a-89ff-95d604e17ec6.png)

The request is to display APMIS dashboard down to cluster level as shown below 
![image](https://user-images.githubusercontent.com/71328926/229869861-b8a83c3a-fe3d-4820-84fa-f80cb1965130.png)
Currently the cluster level dropdown shown above does not work. It is displayed but shows the same data as district so that means it is still pulling district level data. We need the data view down to cluster level.

depends on issue #418 

@sundayAdu @ToluOlayinka @bnygren @RaziaMahmodi

**Comment by bnygren** [comment]
@xlg8 Is any info missing from the issue description still? Can the "needs more info" label be removed?

**Comment by ToluOlayinka** [comment]
> @xlg8 Is any info missing from the issue description still? Can the "needs more info" label be removed?
The Tag was added by the Dev team. we could set up a meeting to discuss more on the issue.

**Comment by xlg8** [comment]
@bnygren @ToluOlayinka SO not more information needed on this issue. It is now clear that the data shown when district is filtered is cluster level and we cannot go below cluster level to sub-cluster reason being that we do not have population data for clusters and lower. We can discuss this today and decide to either close it or adapt it. Thanks

**Comment by xlg8** [comment]
@bnygren We need to add the cluster target from WHO before I can close this issue. We can only test this out from May 2023 campaign once @RaziaMahmodi uploads the cluster target

Thanks

**Comment by sundayAdu** [comment]
It may be more effective to monitor this matter using a different ticket. Currently, our system is configured to only accept population data at the district level. If we were to receive population data at the cluster level, it would require us to redesign the system to accommodate this format. Additionally, it's important to note that the system currently cannot accept target data at the cluster level.
Hence we think this issue be closed.
