### ISSUE TITLE
When mobile user open ICM H2H Household Monitoring checklist app will be restart

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#400]
On Staging server, when mobile user open ICM H2H Household Monitoring checklist app will be restart. (formid=REV_HouseholdMonitoring)

**Comment by RaziaMahmodi** [comment]
I reopen this issues because after the new update, ICM H2H Household Monitoring checklist is not available in web system and won't be open in mobile app.

**Comment by sundayAdu** [comment]
This is rather a typo on the formmeta from the admin and not a bug. The type has been amended here is the cause:
![image](https://user-images.githubusercontent.com/91499626/236422319-14225357-b627-45f0-9b4e-e708f67dd89d.png)

**Comment by RaziaMahmodi** [comment]
Thank you @sundayAdu .
