### ISSUE TITLE
File size for import does not exceed 20mb per import

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#406]
### Bug Description
When you have to import a campaign data for the whole country by forms, say 1 form called PCA H2H has a national data records of 13,200 records, once we download the template and transform the data and import, we get the following error
### Errors produced

1.  File size must not exceed 20mb
2. File size too big for import

### Expected Behavior

We should be able to import data up to 100mb at a time. We need to extend the import limit to as much as we can especially as we are moving into national implementation
### Screenshots

![Image 4-21-23 at 6 11 PM](https://user-images.githubusercontent.com/71328926/233742544-d0885d15-41ab-4f3a-a0a3-bdfa26951175.jpeg)

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information

The solution in the interim is to import the data by regions. But we need to be able to do this once. Please address issue urgently

Thanks

**Comment by bnygren** [comment]
Per discussion today it sounds like there may be an issue with the template file size rather than the data size itself. @xlg8 will follow up. Thanks.

**Comment by bnygren** [comment]
@xlg8 Is this actually a bug? It seems like a change to an existing feature. thanks

**Comment by apmis-org** [comment]
I will remove the bug label. You are right
