### ISSUE TITLE
Remove all other irrelevant languages and retain only English (Afghanistan), Pashto, Dari

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#41]
### Feature Description

Many languages are available that were applied to SORMAS but do not relate to APMIS. 

### Problem Description

Users select "English" as the language (or any other than the three listed) and the admin units are named wrong. 

### Proposed Change

1. Retain only English (Afghanistan), Pashto, Dari. 
2. Remove flag and leave flag blank (or upload blank image if needed)

**Comment by Iyanuu** [comment]
Fixed with commit https://github.com/xlg8/APMIS-Project/commit/733b7a7e86d90852e4ba3088abe6d2aa9a761231
