### ISSUE TITLE
Adding  text "NEOC Afghanistan" under APMIS logo only for EOC_Users

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#410]
Adding NEOC Afghanistan text under APMIS logo. This should be shown only for EOC_Users, Not WHO_Users.

![Image](https://user-images.githubusercontent.com/88741672/234046580-d4807474-ef64-49fc-aec6-8393f780b28c.jpg)

**Comment by ToluOlayinka** [comment]
![Untitled-1](https://user-images.githubusercontent.com/11197190/234548091-7f7b0fe1-0ff9-4a37-b944-da70a77050af.jpg)
 @RaziaMahmodi Wanted to ask if there was a specific font and color. but this was put together
