### ISSUE TITLE
Modify the SORMAS mobile app to remove persistent references to “SORMAS” and show APMIS branding

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#43]

**Comment by bnygren** [comment]
@xlg8 Iyanuu designated this for 'review'. Could you please check it?

**Comment by xlg8** [comment]
@bnygren  On it. Thanks

**Comment by RaziaMahmodi** [comment]
@bnygren, @xlg8, @ToluOlayinka in installation popup windows apmis-1.0.11-debug.apk, the name is still SORMAS.

![photo_2022-03-11_10-04-33](https://user-images.githubusercontent.com/88741672/157910203-a564bb8a-9a65-442e-8046-a67b8c39e62f.jpg)
![photo_2022-03-11_10-04-34](https://user-images.githubusercontent.com/88741672/157910209-b0657601-60f9-4e36-9c93-369584a75bd4.jpg)

**Comment by ToluOlayinka** [comment]
@bnygren @RaziaMahmodi would have this fixed and uploaded.

**Comment by bnygren** [comment]
@ToluOlayinka When apk for 1.0.13 is available, please notify and we can test/confirm. Thanks.

**Comment by xlg8** [comment]
@ToluOlayinka Yes this is now modified to show APMIS and remove persistent references to SORMAS and APMIS branding. I will keep this issue open as the app needs to be updated with the REST API so it can work with all phases. I believe this is beyond the scope of this issue. But will keep it open. Thanks

**Comment by ToluOlayinka** [comment]
> 

This can be closed.

**Comment by ToluOlayinka** [comment]
> @ToluOlayinka @xlg8 @sundayAdu Based on Sunday's demo and comment, can this be reviewed/closed now?
based on the App Demo this can be closed. Going forward the app would have APMIS Branding
