### ISSUE TITLE
There shouldn't be any limitation on accessing pre-campaign and intra-campaign data to EOC_Users

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#434]
1. There shouldn't be any limitation on accessing pre-campaign and intra-campaign data for EOC_Users and Common_Users in Campaign Statistics. (when a campaign is published, it means only Post-campaign data is published to EOC_Users and Common_Users.) 
2. There shouldn't be any limitation on accessing Campaign Statistics data for WHO-Users.

**Comment by sundayAdu** [comment]
This is no longer Campaign statistic on the system. Its been redesigned.
