### ISSUE TITLE
The number of row counts in Configuration should be based on filter

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#435]
When user is selecting from filter, the number of row counts in Configuration (top right corner) is still showing the total number. The number of row counts should count based on filter.  
"No. of provinces:" in Provinces tab.
"No. of districts:" in Districts tab.
"No. of clusters:" in Clusters tab.

![Image](https://user-images.githubusercontent.com/88741672/239040147-8fd6cead-e798-40d8-b260-9eae2d6998fb.png)

**Comment by RaziaMahmodi** [comment]
The No. of clusters: in clusters tab won't work.

**Comment by danieltomabba** [comment]
@bnygren @RaziaMahmodi Filter works on the new UI as is supposed to. However, it is still not working on the legacy system. We should determine if we need to have this done on the legacy system before we can say its done?
