### ISSUE TITLE
Adding FLWs Operation Kit as a tab on Report page

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#448]
A completeness report should be provided for FLWs Operation Kit data:

Data rows with duplicate Tazkira numbers (formid = FLWOperationKit):

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/RMAHMO~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/RMAHMO~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Region | province | district | Cluster Number | ccode | First   Name | Title | Tazkira number | Message
-- | -- | -- | -- | -- | -- | -- | -- | --
East | Kunar | Shegal | 8 | 1306008 | Jalil Ahmad, Ahmad | CS, VOL | 6440687 | Error: Duplicate Tazkira number
East | Laghman | Alingar | 18,   2 | 704018,   704002 | Razia, Nasima | VOL, VOL | 6352397 | Error: Duplicate Tazkira number
East,   West | Laghman,   Herat | Mehtarlam,   Injil | 2,   5 | 701018,   3002005 | Mohammad, Fahim | DC, CS | 7494537 | Error: Duplicate Tazkira number
Central | Kabul | Kabul | 237,   87, 195 | 101237,   101087, 101195 | Karim, Karima, Mariyam | VOL, VOL | 30393789 | Error: Duplicate Tazkira number

</body>

</html>

**Comment by sundayAdu** [comment]
we need more explaination on this ticket...
