### ISSUE TITLE
Expand About section to allow for linking to reference material (e.g., help files/online documents)

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#45]
### Problem Description

We need to expand the About us page with more information about the APMIS system, version numbers, help documents etc.
### Proposed Change

We need to expand the “About section” to allow for linking to reference material (e.g., help files/online documents). We need to extend  and customize the Login and About pages in order to provide the users with information that is specific to your APMIS instance. We will need to redesign the look as well and UI/UX elements.
![3DBE834F-957F-40CB-98D9-7F91525AF785](https://user-images.githubusercontent.com/71328926/135508596-dc0f4411-0148-412e-846e-2ff0ff5eb546.jpeg)

**Comment by bnygren** [comment]
see also #90

**Comment by bnygren** [comment]
@ToluOlayinka @xlg8 Let's discuss the process for updating the listed docs so we can close this issue. Thanks.

**Comment by xlg8** [comment]
@ToluOlayinka expanding into p3.

**Comment by ToluOlayinka** [comment]
> @ToluOlayinka @xlg8 Let's discuss the process for updating the listed docs so we can close this issue. Thanks. 

A single PDF with bookmarks could work. 
Or smaller topic specific PDFs
