### ISSUE TITLE
Legend error: Population data missing when admin data is filtered to cluster level

### ISSUE THREAD

**Issue by apmis-org** [xlg8/APMIS-Project#452]
So, it is assumed that APMIS does not yet import population target data at the cluster level which explains when a user filters down to cluster level to get this legend error on the chart. However, this should only display when a denominator of a chart is set to "Population_0_4" for that error to be applicable. 
The bug here is that, we have a chart with denominator "Total Seen" and the numerator is "Total Children Fingermarked", This should not have anything to do with the population data hence, when a user filters down to cluster level, show the legend based on the defined chart. 

Note: The data generated is correct (% is valid), however, the legend still shows that population error when the cluster level is filtered.

**Comment by danieltomabba** [comment]
This issue has been fixed and we just tested it. Its working as expected. We will have this issue closed now. Thank you.
