### ISSUE TITLE
EOC users should have access to the PCM phase forms

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#453]
Currently EOC users restricted and don't have access to the Post-campaign monitoring phase. 
We want to change their access and EOC users should have access to the PCM phase forms. If EOC users open and enter data to PCM phase, at least they should have access only to the data that they entered. and when PCM phase data published, EOC users are able to see the data.

**Comment by bnygren** [comment]
Waiting on input from country

**Comment by RaziaMahmodi** [comment]
In roadmap. Pending further consideration.

**Comment by RaziaMahmodi** [comment]
Now EOC users are able to have access to data but when PCM phase data published, EOC users should be able to see the data.

**Comment by sundayAdu** [comment]
awaiting @RaziaMahmodi's decision on this matter as it presents a conflict to #603
