### ISSUE TITLE
Import feature should validate data using form logic

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#455]
Current: When importing data, the values are not check against the form's data requirements (e.g., integer range). This allows data to be imported that doesn't meet the requirements for the form and would not have been allowed by web or mobile app entry (potentially degrading the quality of campaign data). 

Requirement: Each row of imported spreadsheet data must be validated against all rules and logic defined for that table in the JSON form; i.e., each imported row will have the same checks as if it was entered in the web or mobile record by record

**Comment by sundayAdu** [comment]
This is not doable.
