### ISSUE TITLE
Need a new method of creating multiple number of Mobile users

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#458]
The current method of creating user and generating password is not ideal for mobile users. 
There is a need for a new method of creating/importing multiple number of mobile users at once. Which can be exported with their passwords (or any secure method for logging in.)

**Comment by RaziaMahmodi** [comment]
Let's change user restriction import template only to Phone Number and not using Email address. Because not all of the users having email address.

**Comment by sundayAdu** [comment]
this was discussed and we think its fixed and should be ready to be closed as the main purpose of requiring an email address in the first place is to enable the forgot password logic which at the moment does to use a Short Messaging Service. Thank you.

**Comment by RaziaMahmodi** [comment]
Not able to import user list. 
![image](https://github.com/AFG-Polio-Data/APMIS-Project/assets/88741672/c064f4bf-a7a5-4720-a4d5-37a925e8fae6)
