### ISSUE TITLE
Enable pre-campaign and post-campaign phases of campaigns for form entry and dashboard

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#46]
### Feature Description

Each campaign has attributes (campaign-level variables) such as name, start date, round. In addition each campaign has data collected for it that relates to the _phase_ of the campaign (i.e., before, during, or after). These phases are:
-Pre-campaign
-Intra-campaign
-Post-Campaign

Essentially this is a subcategory of campaign data that would help classify campaign data-- basically filter forms and dashboard data. The forms themselves are built in the same process regardless of which phase they are associated with. 

New form list (New Form button) is filtered by a dropdown that selects campaign phase (pre-, intra-, post-) 

### Problem Description

Our original project scope was limited to the Intra-campaign monitoring data entry platform, validation and dashboard visualization. Need to include all phases of campaign. 
### Proposed Change

The idea here is to open up the same system to allow users create new forms, edit and configure visualization dashboards for pre-campaign and post-campaign activities and monitoring
![566BE58C-E88F-40F8-89FA-8FC307D36B1F](https://user-images.githubusercontent.com/71328926/135507937-0fc8114d-a8f9-4afa-b9c8-26342067acc3.jpeg)

**Comment by xlg8** [comment]
@ToluOlayinka @Iyanuu Campaign phase filter needs to be included in the campaign directory list as a dropdown to control the overall directory listing. On the dashboard, we require the phase tabs on the right top to be activated.
![image](https://user-images.githubusercontent.com/71328926/156239552-bf4bf858-a058-4367-8b6b-63d2db7a5753.png)

**Comment by xlg8** [comment]
![image](https://user-images.githubusercontent.com/71328926/156239712-939673ac-7a3a-49d0-a441-8f1ca5ffef3b.png)
This is for the campaign directory list for the campaign phase dropdown

**Comment by bnygren** [comment]
Checked 1.0.11, still pending Dashboard and Campaign UI elements as commented by @xlg8 above

**Comment by bnygren** [comment]
@xlg8 @RaziaMahmodi This might benefit from a checkbox list in main description

**Comment by xlg8** [comment]
@ToluOlayinka @sundayAdu @bnygren "All phases" needs to be taken out of the campaign filters and the dashboard filters as well.

**Comment by xlg8** [comment]
Dependency on #136
