### ISSUE TITLE
Date formatting of 'Visit Date' field

### ISSUE THREAD

**Issue by lbaertlein1** [xlg8/APMIS-Project#460]
### Bug Description
The visit date field on all forms allows inconsistently formatted dates to be entered, seemingly from the mobile app. Most dates are formatted as "mm/dd/yyyy hh:mm". However, some are in the format "mm/dd/yyyy", and some are stored as seconds since origin date (i.e. "1684142691000" seconds since 1/1/1970). Can these be forced into a consistent format?

### Steps to Reproduce

1.
2.

### Screenshots

![image](https://github.com/xlg8/APMIS-Project/assets/80183999/f82be3f7-9fdd-47b1-b0aa-ff518fb44b78)

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by sundayAdu** [comment]
We are currently considering the possibility of standardizing the format, but it's important to note that the system accurately stores the data as 1684142691000, representing Mon May 15 2023 09:24:51, rather than the mentioned year (1970). The different format is taking care of by the system during data retrival and manupulation, however, we will be looking at standardizing the raw data as noted.

**Comment by sundayAdu** [comment]
![image](https://github.com/xlg8/APMIS-Project/assets/91499626/834d7274-beea-450f-82a1-576f2021d967)

**Comment by abahsuccess** [comment]
This bug has been fixed a long time ago, and it's surprising that it's still coming from the field. Could this be that some users are still with the old version of the APK? This problem is no longer present on the system. Please Refer to issue #168

**Comment by abahsuccess** [comment]
@RaziaMahmodi @lbaertlein1 Upon reviewing the audits of the data received from the field, we have observed that certain end users are still utilizing an outdated APK to input data into the system. It is possible that they are bypassing the apk upgrade prompt whenever they enter data. It would be beneficial to delve deeper into this matter during today's meeting for further discussion.

![image](https://github.com/xlg8/APMIS-Project/assets/69864014/8daa383b-8345-4bb7-887d-6a565131ad3a)

**Comment by sundayAdu** [comment]
fixed here https://github.com/xlg8/APMIS-Project/issues/168

**Comment by sundayAdu** [comment]
we are changing this to review as this is no longer a bug on the system but rather a end user training issue. Thank you.

**Comment by bnygren** [comment]
@lbaertlein1 @RaziaMahmodi Can this just be closed now? Is there anything to review? (This is basically a function of the discussed app update behavior now.)
