### ISSUE TITLE
Support page is not working

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#461]
- [x] Support page doesn't submit the feedback of users. (bug)
- [x] When users are submitting the feedback, a notification should let users know that their feedback is submitted.

**Comment by abahsuccess** [comment]
This issue has already been resolved.

**Comment by apmis-org** [comment]
I tested this issue on the live server and its working as its supposed to be now.
![image](https://github.com/xlg8/APMIS-Project/assets/71328926/ddc6471b-1b78-4e68-8843-2ccfae0c1e7c)
