### ISSUE TITLE
When deleting a row via bulk actions the pop up confirmation is wrong

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#465]
User sees this when trying to delete a record

![Image](https://github.com/xlg8/APMIS-Project/assets/60660864/9c062511-7143-4c97-a823-a5193fc4633d)

**Comment by danieltomabba** [comment]
@ToluOlayinka @RaziaMahmodi @bnygren This works correctly on the staging and new UI but not updated on the live server

**Comment by danieltomabba** [comment]
I have nmoved this issue to addl development tab until the live server is updated with it. Then we can review it again
