### ISSUE TITLE
Bulk edit button disappears after one use

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#466]
After deleting via bulk actions in Campaign Data page, the "bulk actions" button is gone. User must leave page altogether and return to get the button to reappear.

**Comment by bnygren** [comment]
@RaziaMahmodi Could you please add more description or screenshots to this issue? Thanks.

**Comment by ToluOlayinka** [comment]
@abahsuccess Please check this out.
recreate the instance for both campaign and user management modules
