### ISSUE TITLE
Import allows campaign data for areas that are not in the campaign

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#467]
Import allows data for areas (e.g., Region) that are not in (i.e., not associated with) the campaign. Import should give an error describing that the RCODE/DCODE/CCODE is out of the campaign area, and not allow the entire import.

**Comment by sundayAdu** [comment]
Let's talk about this during our upcoming sprint

**Comment by bnygren** [comment]
All: please add any user-viewable instances of the wrong unit label to the main issue description
