### ISSUE TITLE
User needs to be able to directly edit campaign population through UI

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#469]
Currently, after importing a campaign population, users cannot edit the population, such as to make a change to one value. Sometimes it is necessary to update specific pop values. This should be possible via the UI. Right now, one must access the DB directly to make a change.  

Please add popup or similar requiring user to confirm change showing original and new value.

**Comment by sundayAdu** [comment]
This is already discussed. admin can simply do an export of the data, edit it and upload it back to the system. with this method... its easier to maintain and add / remove any edit the admin want to include.

**Comment by bnygren** [comment]
This approach certainly seems possible but also cumbersome and opens up additional ways for error. The idea is to allow a more user-friendly way for general admins who set up campaigns. Thanks

**Comment by sundayAdu** [comment]
ok
