### ISSUE TITLE
System should not auto-logout user during import

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#472]
Currently system has this behavior: 

- [x] Importing doesn't register as an activity, and it will auto logout the user during a long import
- [x] Displays the warning dialog box about auto-logout behind the import UI/progress window, so user doesn't know they are about to be logged out
- [ ] If the import process is interrupted by auto-logout, the import is partial complete, without the user knowing the number of records (i.e., progress made importing). User is then unable to download the error report either. This also supports removing the problematic partial import behavior #454

**Comment by sundayAdu** [comment]
We have a possible solution to this... we now have a logic that can be configured to provide a seperate logout time for import dialogs. The next worries for us is how long should we delay the logout after the last idle detected?

**Comment by RaziaMahmodi** [comment]
Reopening because import being timed out. 
![import data log out](https://github.com/AFG-Polio-Data/APMIS-Project/assets/88741672/f7bd6b66-7b4f-4932-a848-40f87fc8f996)

**Comment by RaziaMahmodi** [comment]
@Eutit5 Please check this issue with Dev team, system log out during data import on Live server and the "Extend Session" button doesn't work. 

![import Capture](https://github.com/user-attachments/assets/fb41def2-4274-495e-8105-eebf61e0c438)

**Comment by Eutit5** [comment]
@RaziaMahmodi we'll look into it and revert. Thanks
