### ISSUE TITLE
Add campaign-level variable to designate a campaign as a training

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#479]
Currently we have trainings conducted within the live server. This is necessary to prepare for campaigns, but the data should be designated as "not real". This designation can be used to filter out data later, e.g., in an advanced dashboard or a dump of all campaign data. 

It is proposed to add a checkbox or other UI element to the "Campaign Basics" section of the campaign detail page to designate a campaign as a training campaign at the time of creation. Some other visual cue could also help the user know that they are working with a training campaign such as a suffix "[T]" to the title view e.g., "July 2023 training [T]"

**Comment by sundayAdu** [comment]
The administrator has the option to effortlessly append {T} to the end of the campaign name. Once the campaign training is completed, a duplicate can be generated, ensuring that the data is not sent to the new one when the training is concluded. Could this potentially serve as a viable solution?

**Comment by bnygren** [comment]
@sundayAdu Agreed the campaign name can be descriptive but a categorical variable will really help with ensuring filtering data consistently. Discussed with @DevSeg as well. Thanks
