### ISSUE TITLE
Form dropdown list should be sorted based on order in JSON form

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#495]
Forms dropdown list order should be based on the order in JSON forms.

Example 1:
![Image](https://user-images.githubusercontent.com/88741672/260144421-5fd3d15f-2877-47bf-bfe1-55b55a0d9e9b.png)

![Image](https://user-images.githubusercontent.com/88741672/260144560-874fd073-1b34-44fb-8ea2-94b32bd93a6d.png)

Example 2:
![Image](https://user-images.githubusercontent.com/88741672/260144144-42251631-7af1-493a-af83-e5f800bdbf4e.png)

![Image](https://user-images.githubusercontent.com/88741672/260144272-0ecef3e6-f68f-44d8-bc79-5d64b4ee5727.png)

**Comment by sundayAdu** [comment]
This is logically not possible since our data is filled from JSON which is fluid. However, the administrator can solve this problem by making use of sortable keys as they would like the data to be shown to the user e.g numeric values can be added in front of the the keys (1..., 2...)

**Comment by bnygren** [comment]
Thanks @sundayAdu . Let's discuss on a Thursday meeting

**Comment by RaziaMahmodi** [comment]
As per discussion, the better solution can be adding another key as key order to be able to sort the items based of on.

**Comment by DevSeg** [comment]
In order to achieve this, simply add the "order" attribute to the JSON construction as shown in the sample below 
{
    "type": "dropdown",
    "id": "LotClusterNo",
    "caption": "Lot Cluster Number",
    "important": "true",
    "options": [
      {"key":"2","caption":"Sungba","order":"1"},
      {"key":"1","caption":"Zebra","order":"5"},
      {"key":"3","caption":"Monkey","order":"2"},
      {"key":"6","caption":"Frogs","order":"3"},
      {"key":"5","caption":"Toads","order":"4"},
      {"key":"4","caption":"Lions","order":"0"}
    ] 			
  }

**Comment by bnygren** [comment]
@DevSeg great, thanks!
