### ISSUE TITLE
Adding user information in mobile app

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#500]
Adding mobile user profile info in mobile app. By clicking on their name, they should see the details on their profile. like username, their assigned admin units region, province, district, clusters.

![Image](https://user-images.githubusercontent.com/88741672/260462404-94dfafa5-2321-477c-9118-203962072d1e.jpg)

**Comment by bnygren** [comment]
@ToluOlayinka This is labeled review but we are still pending a mobile apk to test per @RaziaMahmodi Thanks.
