### ISSUE TITLE
Export button does not work on campaign data.

### ISSUE THREAD

**Issue by abahsuccess** [xlg8/APMIS-Project#508]
### Bug Description
<Export button does not work when a grid is exported. It gives this error: Failed - Unknown server error. Please try again, or contact the server administrator.>

### Screenshots
<![image](https://github.com/xlg8/APMIS-Project/assets/69864014/ebfefb26-653f-4de9-9730-3aaddf44c207)>

**Comment by ToluOlayinka** [comment]
Tracked on #202 sub sheet
