### ISSUE TITLE
Year dropdown list is showing multiple years in dashboard

### ISSUE THREAD

**Issue by abahsuccess** [xlg8/APMIS-Project#509]
The dropdown list for the year in the dashboard is displaying multiple instances of the same year. This leads to repetitions within the year filter on the dashboard, rather than having only two distinct years as intended.

![image](https://github.com/xlg8/APMIS-Project/assets/69864014/c3fe6880-22ac-499e-bc58-a54f19e9ba41)

**Comment by ToluOlayinka** [comment]
Tracked on #202 sub sheet
