### ISSUE TITLE
Number of data rows selected to delete should be mentioned in campaign data

### ISSUE THREAD

**Issue by abahsuccess** [xlg8/APMIS-Project#510]
When selecting a specific number of campaign data for deletion, the confirmation popup fails to display the quantity of data earmarked for deletion.

### Steps to Reproduce

The confirmation popup should accurately indicate the count of campaigns set for deletion.

![image](https://github.com/xlg8/APMIS-Project/assets/69864014/ae3f29b4-3084-4b9d-926c-0167be492c23)

**Comment by ToluOlayinka** [comment]
Tracked on #202 sub sheet
