### ISSUE TITLE
 Validation for start and end dates is absent across all campaigns.

### ISSUE THREAD

**Issue by abahsuccess** [xlg8/APMIS-Project#513]
Validation for start and end dates is necessary, with a specific criterion that the start date must precede the end date.

### Steps to Reproduce

There should be a logic that checks that the end date selected does not precede the start date

![image](https://github.com/xlg8/APMIS-Project/assets/69864014/e232dd04-3709-4bee-b4db-9a898cc0aaa0)

**Comment by ToluOlayinka** [comment]
Fixed. Tracked on #202 sub sheet
