### ISSUE TITLE
7-day daywise form in mobile app is not complete

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#525]
DC Daily Compilation Sheet Day 1-7 (5-10) has 7 day tab. In mobile app only 4 days are available and the 4 days shows day 7.

id = 1892
formid = AdminCovReport_Day1_7
formname = DC Daily Compilation Sheet Day 1-7 (5-10)

![Image](https://github.com/AFG-Polio-Data/APMIS_Project/assets/88741672/9c2449aa-4def-4ae4-ba76-764e3229ecb6)

![Image](https://github.com/AFG-Polio-Data/APMIS_Project/assets/88741672/af386323-44ff-42e0-908e-5616e9ac6bd5)

![Image](https://github.com/AFG-Polio-Data/APMIS_Project/assets/88741672/54e8d0e0-5d19-4181-8681-8c31923b1a12)

![Image](https://github.com/AFG-Polio-Data/APMIS_Project/assets/88741672/f63cd13c-f79c-49ea-9040-da45564db443)

**Comment by sundayAdu** [comment]
there was a ticket that specifically restricts daywise form to 4days, hence this action was deliberate and not buggy, hence adjusting the label:.
