### ISSUE TITLE
Ensure support for common data input web controls (text box, dropdown, yes/no, radio button, check box) during entry 

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#53]
Culled from https://github.com/xlg8/APMIS-Project/issues/2
### Feature Description
The campaign form module currently supports the definition and entry of number, text and yes-no fields (see #2268 and https://github.com/hzi-braunschweig/SORMAS-Project/wiki/Creating-Form-Definitions-for-Campaigns).

For the APMIS pilot a lot of new forms need to be entered into the system. Some of those forms have the need to provide the user a drop-down select or radio buttons to enter values only from a pre-defined range.

Backend
 Extend json form definition with the new types "select" and "radio" (both are enum kind of types)
 Extend the underlying data structure to support a field "typeValues" that holds a map of "value":"caption" defining all selectable values for that field
 Extend the form translation to also support translation of these value captions
 Implement backend validation for the new field type (triggered when the "validate" button is pressed in the campaigns view).
 Update the documentation accordingly
Example field definition (a translation would look almost the same).

[...
{
	"type": "select",
	"id": "houseType",
	"caption": "Type of house",
	"typeValues": { "HUT" : "Hut", "TOWN_HOUSE" : "Town house", "UNKNOWN" : "Unknown" },
},
...]
Web app
 "select" fields should display a drop-down that allows the user to select one of the defined values
 "radio" fields should display radio buttons that allows the user to select one of the defined values
 When an existing field value does not match the defined values, the existing field value should still be shown
Mobile app
 Synchronize the typeValues definition
 Implement Android backend for the typeValues definition
 "select" fields should display a drop-down that allows the user to select one of the defined values
 "radio" fields should display radio buttons that allows the user to select one of the defined values
Dashboard
 Allow usage of the new field type in campaign diagram definitions. The definition of each series has to define which value is supposed to be used. Example is given below
 The series has to use the name of that value
[...
{
	"fieldId": "houseType",
	"formId": "campaignForm",
	"referenceValue": "HUT"
},
...]

### Problem Description

Currently, APMIS only supports text, number and yes-no data type options. We need to extend the JSON form data types to other data types like radio buttons, dropdown, checkboxes, GIS data etc.
### Possible Alternatives

https://docs.servicenow.com/bundle/paris-servicenow-platform/page/administer/flow-designer/reference/json-parser-step-action-designer.html
E.g 
![image](https://user-images.githubusercontent.com/71328926/135339271-3a46bbbd-d329-4423-943e-1b36e6b70a66.png)

### Additional Information

https://github.com/xlg8/APMIS-Project/issues/2
Ensure support for common data types during entry and storage (integer, decimal, categorical, date, Boolean, Geo code, float in line with common standards)

**Comment by xlg8** [comment]
Expand data collection to include additional form types or non-campaign data

**Comment by cassandraSMART** [comment]
This issue has been fixed with commit: https://github.com/xlg8/APMIS-Project/commit/c7e2f4b7db530919722c899678d3fdb29263d89b
