### ISSUE TITLE
Remove pivot feature

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#534]
Based on feedback, advanced users could use an external analysis tool (e.g., with the API) such as Power BI for this purpose so there is no need to develop one for APMIS.

**Comment by sundayAdu** [comment]
We will suggest different on this issue. the Pivot is one of the most powerful analytics feature we now have on APMIS. It gives the users ability to perform their own customised analytics without needing to plug into PowerBI or Stata or Excel. Apart from that, almost every other Health Informatics System in the industry implement one. We have -in last couple of weeks extend the power of the pivot and improve it grately to not only analyse camapign based analytics. Its now the only efficient cross campaign analytics tool we have on APMIS that can significantly change the way administrators and users manipulate and interpreates their data. We will strongly implore the Technical team to allow this wonderful feature to remine on the system. Its will only add value to the system in General.

**Comment by sundayAdu** [comment]
suspended

**Comment by bnygren** [comment]
Thanks. It is a nice feature, but not a priority at this time. We can revisit later.
