### ISSUE TITLE
Ensure support for calculations within data entry pages/forms based on entered data within that form

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#54]
### Situation Description

Culled from https://github.com/xlg8/APMIS-Project/issues/2
Currently, when we enter numeric data entries which have variables of interest which contain some type of calculations, the calculated field cannot be displayed automatically without first achieving this during form creation. The calculation feature on APMIS should be improved.

The campaign form module currently supports the definition and entry of number, text and yes-no fields (see #2268 and https://github.com/hzi-braunschweig/SORMAS-Project/wiki/Creating-Form-Definitions-for-Campaigns).

For the APMIS pilot a lot of new forms need to be entered into the system. Some of those forms have the need to provide the user a drop-down select or radio buttons to enter values only from a pre-defined range.

### Feature Description

As an addition to https://github.com/hzi-braunschweig/SORMAS-Project/issues/5372, we need to be able to support calculations within data entry pages as the data is being entered live. E.g. If a provincial level officer is creating a form data entry, and he enters 450 children seen, 350 children absent, 100 children on street, the total number of children within that household or cluster should be calculated on displayed within the total children field. Other types of calculations like logical functions, should also be applicable.

### Additional Information

Support for basic logical checks on input (range checks, agreement between fields)

**Comment by bnygren** [comment]
Can this be closed?

**Comment by xlg8** [comment]
Yes we can close it
