### ISSUE TITLE
Import template file name should be specific

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#551]
The file name of the import template should be clear and based on the name of the form and campaign or system section that we want to import the data. (like the name of Export templates.)

**Comment by sundayAdu** [comment]
we cannot reproduce this issue

**Comment by bnygren** [comment]
@RaziaMahmodi @sundayAdu I cannot reproduce either. I checked the templates for all forms by downloading each file and they all follow the convention Campaign__formname.csv

**Comment by bnygren** [comment]
@RaziaMahmodi Is this issue perhaps mis-stated as applying to import when in fact it is about exports? Data exports are simply: "Campaign_Form_DataDate.csv" e.g., Campaign_Form_Data20232510.csv
