### ISSUE TITLE
Target population on cards (PopAge_0_4) should default to only activated regions based on "Associate Campaign" selection

### ISSUE THREAD

**Issue by danieltomabba** [xlg8/APMIS-Project#558]
### Feature Description

The cards for Admin Coverage based on Total Children Vaccinated divided by Target population is displaying a wrong data output. The target population should not be the total overall national target population when a campaign is a CRC or SNID. The target population should be controlled by the subset selection under "Associate Campaign" after the user must have imported the National target population default data.
### Problem Description

We have an issue that the cards on the dashboard are erroneous. The data varies between admin coverage (intra) on the APMIS native and admin coverage (intra) on Shiny, The reason is that shiny has set its denominator for targeted children to be a subset of only the regions implementing within a specific campaign which is the accurate situation. Depending on whether it's a CRC, or SNID which specifies only implementing regions. 

However in APMIS, even though we have imported the default national campaign, you have the target population to be 11,000,000 even for CRC and SNIDs or if not imported only for the East region. That should not be the case. The APMIS native should show the target population denominator subset based on activated regions under "Associate Campaign". Right now, it just shows the total target population based on the default import. I will kindly suggest that this subset issue be fixed and we might have to deactivate the cards on the APMIS native in the meantime. Thank you.
### Proposed Change

Ensure that the target population on the cards which is a denominator for card calculation should be displayed based on the total target population selected from "Associate Campaign" in the campaign data settings. @bnygren @ToluOlayinka @sundayAdu @RaziaMahmodi 
### Possible Alternatives

NA
### Additional Information

![Image 10-27-23 at 4 00 PM](https://github.com/AFG-Polio-Data/APMIS-Project/assets/135902076/371b6879-0fb0-457a-9ad1-b8284a859088)

**Comment by danieltomabba** [comment]
I tested this and realized that when you click on a region checkbox under associate campaigns, it does not automatically deactivate or activate the provinces or districts and the same thing for when you click on a province, it does not deactivate or activate the districts- This is needed to ensure that the target population on the cards respond to the correct selection of only active regions based on the associate campaigns selection

Also found this bug that even though the language is defaulted to English for my logged-in user, under associate campaigns, the labels are in Pashtu or Dari- not sure which language.

**Comment by sundayAdu** [comment]
@danieltomabba could you create another issue for this bug / comment so that we can properly reference it. The current issue is mainly based on dashboard and we will suggest the issue raised is around campaign edit module.

**Comment by bnygren** [comment]
Not tested, but will close until otherwise noted as needing review. The current dashboard will likely be superseded by improved visualization tools.
