### ISSUE TITLE
UI form builder requirements

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#561]
Rather than coding JSON and inserting form definitions into postgreSQL via DBeaver/pgadmin, there is a need for a UI-managed form builder.

Requirements: 

- create a form
- input form metadata/properties ( form name, phase, modality, etc.)
- create form elements: define variables IDs, variable types (text, label, number, dropdown, etc.), captions, options, validation, translation)
- translating form name
- edit an existing form
- archive/remove a form? (consider implications)
- preview and test the form without adding to a campaign (i.e., practice data entry data goes nowhere)

**Comment by RaziaMahmodi** [comment]
The New Form button doesn't work. Also tabs are not showing. They are showing only while mouse hover.
