### ISSUE TITLE
Adjust Linode tier of Test server

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#566]
Test does not need to be at the same tier as Live. Please set to the same tier as Staging. It has by far the least usage of the three. 

![Image](https://github.com/AFG-Polio-Data/APMIS-Project/assets/60660864/e02bd2d0-91f6-404c-9b25-7d047aa36efa)

**Comment by ToluOlayinka** [comment]
Based on Conversations on Slack.
Test can be downgraded to 8GB (Linode).

**Comment by bnygren** [comment]
Thanks @ToluOlayinka Sounds fine to me. It would actually be useful to compare the perceived performance (speed) of each of the servers when they are on different tiers.

**Comment by bnygren** [comment]
I made the change
