### ISSUE TITLE
Cluster Number and CCode shouldn't be listed for District level forms

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#572]
Cluster Number and CCode shouldn't be listed for District level forms in Campaign Data list. 

![Image](https://github.com/AFG-Polio-Data/APMIS-Project/assets/88741672/edcbe929-5107-4fee-876c-599045c7c597)

**Comment by RaziaMahmodi** [comment]
When data is listing based on All columns or Importance, the Cluster Number and CCode will be listing as well.

**Comment by bnygren** [comment]
@RaziaMahmodi Which forms are included as district-level? Confirmed this is working (only down to DCode now showing) for the form FLWs Operation Kit DC. The other 2 precampaign forms still have cluster and CCode.

**Comment by bnygren** [comment]
@RaziaMahmodi Which forms are included as district-level? Confirmed this is working (only down to DCode now showing) for the form FLWs Operation Kit DC. The other 2 precampaign forms still have cluster and CCode.

**Comment by RaziaMahmodi** [comment]
> @RaziaMahmodi Which forms are included as district-level? Confirmed this is working (only down to DCode now showing) for the form FLWs Operation Kit DC. The other 2 precampaign forms still have cluster and CCode.

Those forms that are marked in DB (districtentry) as district level forms.
