### ISSUE TITLE
Username must be unique for users

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#575]
There is multiple users with the same username. Maybe it is an bug that repeatedly shows the username. "Kindly check the issue as I can see that there are other users as well. One thing more, that some of these users (Asif Durrani’s) are not working, even I changed the password but still not signing in.

![Image](https://github.com/AFG-Polio-Data/APMIS-Project/assets/88741672/f624dfec-3c84-46a3-a724-184c59e03e65)

**Comment by naveeddil** [comment]
One thing more that there are spaces accepted in usernames whihc should not be allowed.
