### ISSUE TITLE
Users receive error while log in related to EAG forms

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#580]
**This issue is on Live server.** 
It seems that users that are assigned to EAG forms categories, are not able to log in and receive this error. This error occur when the  form category in DB is defined as EAG-ICM, EAG-PCA ... . But if the form category in DB is defined as only EAG, user is able to log in with no error. Also, forms are available and user able to enter data. 

**Form category in DB should be defined as EAG-ICM, EAG-PCA, ... and users should log in with no error.** 

![Image](https://github.com/AFG-Polio-Data/APMIS-Project/assets/88741672/ede746e1-cc6f-4da7-9fe0-a815d1887919)

**Comment by sundayAdu** [comment]
This was fixed immediately after redeployment and a stop gap was introduced to the campaignformmeta to restrict the input of "-" in the formcategory column. Admin are required to use "_" instead of "-".
