### ISSUE TITLE
remove https://staging.afghanistan-apmis.com/analytics URL

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#588]
correct URL is 

/analytics leads to a skeletal app

need to 
- remove /analytics URL (keeping /main/analytics)
- remove old app

![Image](https://github.com/AFG-Polio-Data/APMIS-Project/assets/60660864/4aeaf9e0-5999-4a56-8fad-050cde9af5cf)

**Comment by danieltomabba** [comment]
Tested and done
