### ISSUE TITLE
Variable names row missing from csv exports

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#589]
Variable names (e.g., T0_59_M) row is missing from campaign data exports. Only labels (e.g., Total children 0-59 months at home) are showing now. Previously there were variable names and labels. Not having variable names makes it difficult to use the data as the captions are not necessarily unique. Please add the variable names row back in. 

Previous export: 
![image](https://github.com/AFG-Polio-Data/APMIS-Project/assets/60660864/24d93622-c8f6-4e84-b073-4a6b52fa16e0)

Current export:
![image](https://github.com/AFG-Polio-Data/APMIS-Project/assets/60660864/d5bf472d-d735-48ba-8262-8eef8db6404d)

**Comment by RaziaMahmodi** [comment]
@bnygren Please provide more information.

**Comment by bnygren** [comment]
Sorry @RaziaMahmodi what is missing in the description? Does this help?

**Comment by RaziaMahmodi** [comment]
> Sorry @RaziaMahmodi what is missing in the description? Does this help?

Sunday needed more information. The description isn't clear for him.

**Comment by kolemartins** [comment]
@bnygren we are asking if we should adjust the export to include the two rows as described above in img1 or just the variable label from the metadata.

**Comment by bnygren** [comment]
@kolemartins The 2 rows (variable name and label) as shown in the image. Thanks.

**Comment by bnygren** [comment]
currently unable to export any data from staging to test this (as also commented in slack)

**Comment by ToluOlayinka** [comment]
We've identified and resolved the bug, and the fix will be included in the next staging push.

**Comment by bnygren** [comment]
Hi @ToluOlayinka If this is fixed (even though we cannot test on staging), please update this fix on Live. Let's coordinate with @RaziaMahmodi for the best time as soon as is feasible. The campaign is next week, and surely there will be a need to export data with the correct headers for analysis. Thank you.

**Comment by sundayAdu** [comment]
@bnygren this is understood and will be hotfixed on the live server.

**Comment by bnygren** [comment]
Thanks @sundayAdu !
