### ISSUE TITLE
Translating the form names in system

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#591]
https://docs.google.com/spreadsheets/d/15pkVjVClGaHHOZi2RN9TKaEHgFdg3InJmoH2RCq1NF8/edit#gid=481605273

**Comment by RaziaMahmodi** [comment]
Form UUID is added.

**Comment by bnygren** [comment]
Tested with 1 intracampaign and 1 postcampaign form. seems to be working correctly.
