### ISSUE TITLE
Setting validation rule on LQAS lot cluster number

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#600]
Restrict system and mobile application to submit only 6 Lot Clusters Number (ranging from 1-6) for each Lot Number in LQAS form. It means user is not allowed submit/enter more than one data row per lot cluster number per lot number. 
formid = LQAS

Also: Within the district, each cluster number must be unique (e.g., district "A" cannot have cluster number 2 more than once). 

similar to issue #219 

![image](https://github.com/AFG-Polio-Data/APMIS-Project/assets/88741672/56bc0df4-caff-4c3f-a6ba-8e2cb1872848)

Error:
![image](https://github.com/AFG-Polio-Data/APMIS-Project/assets/88741672/7fe1fcd3-89c3-4759-b64e-b264a7cff0ce)

**Comment by sundayAdu** [comment]
This is essentially impractical as long as mobile devices retain offline capabilities. There is no mechanism in place for one device to be aware if another device has inputted the same data from the six available lots in offline mode.

**Comment by RaziaMahmodi** [comment]
User is still able to submit 2 lot cluster number data record for the same cluster number.

**Comment by RaziaMahmodi** [comment]
This issue is fixed on web system, but it doesn't work on mobile app.
