### ISSUE TITLE
Flexible form builder component based on existing JSON forms and ability to create, duplicate new forms

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#62]
### Feature Description

Culled from https://github.com/hzi-braunschweig/SORMAS-Project/issues/3094 and related to https://github.com/xlg8/APMIS-Project/issues/6
### Problem Description

Currently, we have all JSON form definitions as raw JSON codes in the database which a technical person needs to edit, re-write and create new form definitions within PostgreSQL. Campaign forms are bound to change from campaign to campaign. Hence, we need the country focal persons who create campaigns to be able to edit an existing forms using a flexible form UI editor. 
### Proposed Change

A flexible form builder component (generic json form builder UI-template) is required to be created using a form editor framework. The form builder should allow users to build the form as a JSON schema which will render as a form in the APMIS application which will connect to the database while previewing the form to the users. Some examples are Form.io is an open
source application (https://github.com/formio/formio).
### Possible Alternatives

https://codepen.io/travist/full/xVyMjo/
![BDA094E4-D5EE-4528-9F80-2F1EB7F10FB2](https://user-images.githubusercontent.com/71328926/135321134-cb295d9f-1a7d-4c44-ac10-89d40b106d0c.jpeg)
This would be how we want the JSON form builder to work. GUI for creating JSON form definitions http://docs.smarthealthit.org/fred/

![image](https://user-images.githubusercontent.com/71328926/135470659-3978a478-fe23-4912-a57a-4cd437bc06ec.png)
![image](https://user-images.githubusercontent.com/71328926/135470688-2f8897a8-8f30-4c03-9fcf-8404155850a8.png)

### Additional Information

Add simple screen for building data input forms via GUI

**Comment by bnygren** [comment]
see #6 #60 #61

**Comment by bnygren** [comment]
@xlg8 Closing since forms should not regularly change and there would not be a need for this.
