### ISSUE TITLE
Configuration: Active status should be included in column exports and grid view

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#629]
Active status should be represented in config data (all admin unite tabs). This helps in tracking changes to clusters particularly. 

- [ ] Add a column to the "grid"/list view showing active as a column
- [ ] Include the status (Active/Archived) in the csv export  

On initial page load, please also show "active" in the dropdown filter value as we are defaulting to active records in the grid. 

![Image](https://github.com/AFG-Polio-Data/APMIS-Project/assets/60660864/6c011124-a355-4427-94da-ff7015e12f06)

**Comment by bnygren** [comment]
Edited as discussed 20 March. Thanks.
