### ISSUE TITLE
Add ability to duplicate campaign configurations from an existing campaign to a new one ('Clone' button)

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#63]
### Situation Description

Culled from https://github.com/hzi-braunschweig/SORMAS-Project/issues/3290
After each new campaign is created, the user has to configure all charts and forms. The feature does not allow new campaign data charts and even when changed from the database, the whole dashboard view buttons disappear leaving only one category

- [x] Clone button should be in campaign edit/detail, not its own col (see also https://github.com/xlg8/APMIS-Project/issues/27)
- [x] Clone button doesn't work - single click does nothing; dbl click opens edit page

### Feature Description

The system should be able to duplicate an existing campaign configuration for future campaigns. (i.e., copy a previous campaign’s configuration and rename, then edit as needed)
The feature should allow new data charts and forms to be added to the system.
### Additional Information

![image](https://user-images.githubusercontent.com/71328926/135318954-e01c3e11-40bc-4194-98ea-8adc5e3e5d1f.png)

**Comment by bnygren** [comment]
Clone button non-functional in 1.0.8

**Comment by bnygren** [comment]
Clone button requires double-click which seems counter intuitive given the row highlight and mouseover behavior. Maybe the clone button would be better in campaign detail, next to 'archive' and 'delete'

**Comment by Iyanuu** [comment]
During the sprint meeting, a suggestion was raised to change the duplicate campaign identifier to exclude 'DUP'. Rather a completely new UUID is generated to identify the duplicated campaign.

**Comment by Iyanuu** [comment]
@ToluOlayinka @bnygren @xlg8
