### ISSUE TITLE
JSON mapping console for linking relational variables within the defined database (PostgreSQL in our case)

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#64]
### Problem Description

JSON data currently is stored as transactional data in the PostgreSQL database. For integration with visualization components like Metabase or PivotJS, we need to map the JSON transactional data into a JSON relational data set and link the relational data frame  into another PostgreSQL table within the same APMIS database. All dashboard definitions queried from the database will be through the JSON relational table for form data. 
### Proposed Change

Create a JSON mapping console as a cron-job service to migrate JSON transactional data to relational data within the same database. Ensure that the JSON transactional data table still remains active and collects JSON data from the JSON form definition while transmitting the corresponding JSON data into a relational table within the same DB.
### Possible Alternatives

https://visualstudiomagazine.com/articles/2021/06/04/converting-json-2.aspx
Declare @json NVarChar(MAX) = N'
{
 {
  "customers" : 
  [
   {"id" : "A123",
    "createdOn" : "2021-05-19T15:10:48.852073Z",
    "salesToDate" : {
          "amount" : "2040.15",
          "currency" : "USD"
    },
    "addresses" : [
        {
            "type" : "Billing",
            "street" : "500 Ridout St."
        },
        {
            "type" : "Shipping",
            "street" : "300 Strathcona"
        }
    ]       
  },
  …more customer objects…
]}';
### Additional Information

Declare @tSales Table (id nvarchar(100), amount decimal(7,2), currency nvarchar(3) );
Insert into @tSales
  Select * From
    OpenJson(@CustomerHold) with (id nvarchar(100), 
                                  amount decimal(7,2) '$.salesToDate.amount', 
                                  currency nvarchar(3) '$.salesToDate.currency');

**Comment by ToluOlayinka** [comment]
@bnygren I think this has been resolved. @sundayAdu ??

**Comment by xlg8** [comment]
Yes this has been resolved during the API development. We can close this now.

**Comment by ToluOlayinka** [comment]
based on comment. this is closed
