### ISSUE TITLE
Not able to import population to campaing

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#642]
Not able to import population data to a campaign. Bellow error will be appeared. 

![Image](https://github.com/AFG-Polio-Data/APMIS-Project/assets/88741672/5f960d8f-ff3e-438b-a309-9230607d5628)
![Image](https://github.com/AFG-Polio-Data/APMIS-Project/assets/88741672/552bc715-5efb-4c52-87fe-b07555cdda51)

**Comment by naveeddil** [comment]
Colleagues, if fixing auto import is taking long so we need to have alternate to import the data

**Comment by RaziaMahmodi** [comment]
Live server is updated today, APMIS Version Number:: 4.0.1 - Release Date:: 14|05|2024
This issue is fixed on Test server, but it still exists on Live server.  

![Image](https://github.com/AFG-Polio-Data/APMIS-Project/assets/88741672/b9b00bbc-75fb-4921-926e-1e4d7ec2e407)

**Comment by RaziaMahmodi** [comment]
@DevSeg 
Hi,
With new update on live server, not able to import the population to campaign. This is working on Test server. But not working on Live server. 

![image](https://github.com/user-attachments/assets/77aa4bf5-32f9-48c8-8714-142cc398d0f7)
