### ISSUE TITLE
Row-wise ("Line list")/tabular entry mode 

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#65]
### Situation Description

Currently forms are entered in a "sheet" view; each record is a form roughly similar to a paper form. This may limit users who have a number of forms to efficiently extract

### Feature Description

Add a mode to allow entry across rows in a tabular fashion. User can tab to the next row to add an additional record of the same type on the same screen. 

### Possible Alternatives

We can customize and configure the SORMAS linelisting feature for this request. Ensuring that users can enter data record by record on the same screen and bulk submit
![AA790886-5FD2-4147-B546-5D82E2D2B76B](https://user-images.githubusercontent.com/71328926/135469853-6a46125a-1bdd-4b5a-a201-fe054afa9ca3.jpeg)

**Comment by Iyanuu** [comment]
@ToluOlayinka @bnygren The dev team thinks this has been resolved with the "Add and New" functionality.

**Comment by xlg8** [comment]
Based on the "SAVE and ADD NEW feature", we can apply this to the line list entry mode. So we can close this issue as well. Thanks

**Comment by bnygren** [comment]
Moved to roadmap for consideration. This wasn't assigned to anyone on dev team yet. It's a different feature than "save and add new" but perhaps the demand no longer exists for it if users feel the existing data entry tools meet their needs.

**Comment by xlg8** [comment]
@bnygren Thanks. Agreed. But the request was done when SAVE and ADD New feature was developed. A line list would want to limit the number of variables but we actually want to have all the variables defined. Hence the Save and add new feature. See diagram for the line list which only takes into account a limited number of variables for rapid data entry
![image](https://user-images.githubusercontent.com/71328926/183444644-6b313ff7-b838-4a44-8382-83a7ab567c60.png)
