### ISSUE TITLE
Add attribute to clusters: "Floating"

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#650]
Please add attribute (variable) to clusters named "Floating" which has 2 allowed values; "Floating" and "Normal". 

Add a dropdown filter Configuration / Cluster view next to "Active" status to allow filtering by Floating status.

**Comment by RaziaMahmodi** [comment]
@DevSeg Include the cluster floating status to the import cluster template, the floating status field is required like other fields. 
Default status for clusters should be "normal".
