### ISSUE TITLE
Remove the SORMAS items from mobile app

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#658]
Remove the SORMAS items on mobile app menu, Tasks, Cases, mSERS, Contacts, Events, Samples, Reports. 

![Image](https://github.com/AFG-Polio-Data/APMIS-Project/assets/88741672/e60e269c-e403-4940-8a52-e6c263fd0d67)

![Image](https://github.com/AFG-Polio-Data/APMIS-Project/assets/88741672/b9d1e214-0092-4261-86bc-cac62d62cabd)

**Comment by sundayAdu** [comment]
This is long fixed... and only affect very old apk. Please update the apk and this will be resolved

**Comment by RaziaMahmodi** [comment]
It is still showing in app version 34 for district level mobile users.
