### ISSUE TITLE
Allow custom tab layout in form view

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#66]
### Situation Description

Forms that have same attributes for days 1-7 reporting should be split into tabs for easy data entry or save and add new feature used to add new forms for each day making day filter required. 

### Feature Description

Suggestion: it is better to design it as a drop drown for each day (we can able to select day one, day two, day three & day four, up to day seven).   

Separate the days by save and add new or by tabs. At the end of Day1-Daily Compilation Sheet, suddenly Day2-Daily Compilation Sheet is written it indicates that this is part of Day1-Daily Compilation Sheet, which should be separated from each other even with different tab.  

 
![8BB8C9B6-2686-49F4-A70A-61643DB3053D](https://user-images.githubusercontent.com/71328926/159782246-18ff6eb7-37cc-43d6-9dc9-2d68d2917bc8.jpeg)

 

 

### Additional Information

![F02C65E1-C562-4D57-85AE-65D8C136A0DB_4_5005_c](https://user-images.githubusercontent.com/71328926/159782645-c9e62de8-6c6a-4149-b022-14aecc24baff.jpeg)

**Comment by xlg8** [comment]
@sundayAdu Please let me know if you have any questions about this issue. Thanks

**Comment by xlg8** [comment]
@bnygren @ToluOlayinka @RaziaMahmodi We like the option for tabs instead of colors as suggested in last meeting. Please proceed as suggested

**Comment by xlg8** [comment]
@bnygren @RaziaMahmodi We should move this to P3 while concentrating on compilation sheets and import schedule. What do you think? I will create the issues regarding that. I have been trying to do some data import and ran into issues with mis-matching records

**Comment by sundayAdu** [comment]
@bnygren presently there is no attribute to specify if a form is day 1-7, can we add this to form definition? or is there a particular form or forms that are 1-7days normally?

**Comment by bnygren** [comment]
@xlg8 @RaziaMahmodi Can you address the above comment please?

**Comment by RaziaMahmodi** [comment]
> @bnygren presently there is no attribute to specify if a form is day 1-7, can we add this to form definition? or is there a particular form or forms that are 1-7days normally?

@bnygren 
@xlg8 
@sundayAdu 

These are forms (in main server) that have days 1-4:
DC Daily Compilation Sheet H2H => days 1,2,3
DC Revisit Compilation Sheet H2H => day 4

Currently, vaccine coverage data is made/divided in these two forms. A solution is needed that combines these two forms to one form. And for entering data, user can switch between days (as we referred as Tab in the issue description).

**Comment by Iyanuu** [comment]
Hi @RaziaMahmodi 
Thanks for the explanation. Do you want the form to be aggregated at the end of the day or disaggregated by days when you view the data?

**Comment by Iyanuu** [comment]
Also, how does the user enter the data? Are they allowed to enter all data on the same day or save the day before proceeding to the next? When proceeding to the next, will they be reopening the saved data to add the next day or just the next tab?

**Comment by abahsuccess** [comment]
**PROPOSED SOLUTION**
1. Create an option for multi-day attributes in the form JSON.
2. Patch the necessary classes to enable the attributes filter.
3. Implement Vaadin TabSheet.
4. Test and deploy

_This will be adjusted to reflect the response to @Iyanuu _

**Comment by RaziaMahmodi** [comment]
> Hi @RaziaMahmodi Thanks for the explanation. Do you want the form to be aggregated at the end of the day or disaggregated by days when you view the data?

@bnygren 
@xlg8 
@Iyanuu in reply to your 2 comments:

I think for viewing/aggregating dataset/rows we are flexible for whatever is user friendly solutions. also we will discuss on this part to provide you more info.
What is really important is that data must be linked up based on being from same region, province, district and most importantly **cluster number**.
Some fields value in day 4 are the calculation result of some fields from Day 1,2,3. For example West region, Hirat province, Injil district, _Cluster 10_:
_Number of children Remaining Refusal_ from Day1, 
plus
_Number of children Remaining Refusal_ from Day 2
plus
_Number of children Remaining Refusal_ from Day 3
equal or to be shown in
_Number of children Remaining Refusal (Day 1-3)_ in Day 4

**Comment by RaziaMahmodi** [comment]
>

> Also, how does the user enter the data? Are they allowed to enter all data on the same day or save the day before proceeding to the next? When proceeding to the next, will they be reopening the saved data to add the next day or just the next tab?

@bnygren 
@xlg8 
@Iyanuu 

About how user can enter the data:
Are they allowed to enter all data on the same day or save the day before proceeding to the next? **Both are possible.** 
_But users to be allowed to enter all data on the same day is the most possible._

When proceeding to the next, will they be reopening the saved data to add the next day or just the next tab? It seems a good idea that when users want to add the next day, they will be able to reopen/switch/review the saved data as well.

I will provide you more information after more research on these 2 questions.
