### ISSUE TITLE
API campaignformdatacount error

### ISSUE THREAD

**Issue by lbaertlein1** [xlg8/APMIS-Project#679]
### Bug Description

The API endpoint "campaignformdatacount" is not returning the expected results. It is expected to return to the total number of rows currently in the campaignformdata table. However, it returns the number of non-archived rows. Since the "campaignformdata" API endpoint does not limit the return to only non-archived rows, these two are out of sync. Adjust "campaginformdatacount" so that it returns the total number of rows in the campaignformdata table, including both archived and non-archived rows.

### Steps to Reproduce

1. URL to get campaignformdatacount: https://afghanistan-apmis.com/sormas-rest/apmisrestserver/campaignformdatacount
2. URL to get campaignformdata: https://afghanistan-apmis.com/sormas-rest/apmisrestserver/campaignformdata
3. Compare the number of rows returned by campaignformdata to the value returned by campaignformdatacount. They should be the same.

**Comment by lbaertlein1** [comment]
Tested on live APMIS - issue not yet resolved on Jul 29th

**Comment by DevSeg** [comment]
https://github.com/AFG-Polio-Data/APMIS-Project/issues/680#issuecomment-2257237684

**Comment by lbaertlein1** [comment]
Tested on Test APMIS - issue is resolved on Test as of Jul 30th
