### ISSUE TITLE
API for 'campaignformdata' error in returned 'isPublished' and 'isVerified' fields

### ISSUE THREAD

**Issue by lbaertlein1** [xlg8/APMIS-Project#680]
### Bug Description
The campaignformdata API returns data from the campaignformdata table, including the fields 'isPublished' and 'isVerified'. However, these are universally returned as False, when the values in APMIS are a combination of True and False.

### Steps to Reproduce

1. Compare the data returned by the campaignformdata API endpoint for the 'Feb SNID 2024' campaign to the same data viewed within APMIS. The LQAS form has 980 records. By the API, all of these have isVerified and isPublished set to FALSE. Within APMIS, 151 are Published and 250 are Verified. These published and verified statuses of records should match between APMIS and what's returned through the API.

**Comment by lbaertlein1** [comment]
Tested on live APMIS - issue not yet resolved on Jul 29th

**Comment by DevSeg** [comment]
Hi @lbaertlein1 . The issue needs to be tested on the test portal before being pushed to live. Please conduct the testing on the test portal first to ensure the resolution before  moving to the live environment.

**Comment by lbaertlein1** [comment]
Tested on Test APMIS - issue is resolved on Test as of Jul 30th
