### ISSUE TITLE
Configure new (3rd) server for testing of same build as Live

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#684]
**Situation**: APMIS currently has 2 servers, Live and Test. While Test provides an opportunity to see new features, we lack an environment to test the current build without real data. This limits testing on the Live system. Additionally there is a need for a clone of the Live system to allow for training sessions and testing of the Live build by advanced users. 

**Proposed solution**: Maintain a third sever that has the same build as Live (i.e., when Live is updated the 3rd server also is). Per CS suggestion, when a software update is ready for Live, this server should be updated with the software first. Then Live will be updated next. This would allow for further testing of the software that is designated for Live, while Test can continue to be updated with new features to review. 

**Naming**: Training server. 

**Server Data:** Data will be copied from Live server periodically. Exact timing TBD

**Comment by bnygren** [comment]
@Eutit5 We travel to the APMIS meetings next week, so we will need to set this up by the end of this week please. Thanks

**Comment by bnygren** [comment]
@RaziaMahmodi can we remove the pending discussion label? Is there anything else to determine for this? Thanks

**Comment by Eutit5** [comment]
@bnygren this is currently in progress, should be completed by tomorrow.

**Comment by bnygren** [comment]
Great. Thanks @Eutit5 !

**Comment by DevSeg** [comment]
Hi @bnygren this requirement has currently been completed. we have now configured a new training server which is a mirror of the current live environment and would be maintained alongside the live server. @Eutit5 would provide further updates.
