### ISSUE TITLE
Delete button in Associate Campaign delete the selected DCode not selected row

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#689]
Delete button in Associate Campaign doesn't delete only the wrong/duplicate rows, it deletes every row of the selected district (DCode) even not selected rows (correct rows).

![Image](https://github.com/user-attachments/assets/382256c0-010b-435d-ba02-5b8556ce86f8)

**Comment by DevSeg** [comment]
Hi @RaziaMahmodi, based on the requirements surrounding this issue, we kindly request that it be treated as an improvement rather than a bug, given the functionality involved with how the delete button operates. Thank you for your understanding.
