### ISSUE TITLE
user login deactivation after extended time period

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#691]
If a user has not used APMIS for an extended time period (TBD) the user account should be deactivated. To reactivate the user should contact an admin. 

Behavior: 
1. have not logged in for 9 months
2. try to log in
3. get an error msg stating "Your account is deactivated since you have not logged in for a long time. Please contact your administrator to reactivate your account."

**Comment by DevSeg** [comment]
Regarding this issue , it has been agreed that we set the timeframe of user deactivation to an expiry period of 9 months, Additionally, we are to be provided with a specific email address for user to contact for reactivation.

**Comment by bnygren** [comment]
Thanks, @DevSeg We will have the contact email figured shortly

**Comment by bnygren** [comment]
@DevSeg we decided not to include a specific email as it will vary depending on the user. Please see updated issue description.

**Comment by DevSeg** [comment]
Thank you @bnygren that's well noted, we would update the feature to accommodate the new description.

**Comment by bnygren** [comment]
How can we best confirm/test this and close the issue?

**Comment by bnygren** [comment]
Hi @DevSeg @Eutit5 , Following up on this -- How should we test this and close? Can you please direct us to a particular user in test that is set up as "timed out" to try logging in as that would show the functionality? thanks

**Comment by DevSeg** [comment]
Sure @bnygren we'll deactivate a user and share the user credentials, if we're aware after testing, we can go back to enable that user for confirmation.

**Comment by bnygren** [comment]
Confirmed
