### ISSUE TITLE
Multiselect filter for roles dropdown in user list

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#692]
When viewing the users list, it is a challenge to filter by desired role criteria. There are so many mobile users that we would like to filter them out but view other combinations of users. e.g., everyone who is not mobile/FLW. Ideal solution would be a multi-select UI element similar to an excel table header filter, rather than a single select dropdown.

**Comment by bnygren** [comment]
confirmed
