### ISSUE TITLE
Population import fields should be required

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#695]
Population import template fields should be required.

**Comment by bnygren** [comment]
In attempting to test this issue I get an error message as pasted below. Steps taken: download tempate, fill in but leave some missing col values, tick overwrite, import dry run. Please advise. 

![Image](https://github.com/user-attachments/assets/c6b7e5d7-9f6c-4211-8b03-4858b9dcc54b)

**Comment by bnygren** [comment]
Marked this as not complete until we clarify the above error
