### ISSUE TITLE
Forms need to support logical checks

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#70]
related to #54 
### Situation Description

Users will enter data that is out of range or fails logical test. 

### Feature Description

Need to be able to perform logical check at time of entry including:

- [x] **Warn user:**
•	As a result of a failed logical test, system should either:
o	Allow a popup prompt of "Allow Value",
o	Prevent entry of illegal value,
o	Highlighting the error field with the short warning message to user.
•	Ability to customize Warning Message.

- [x] **Required Field:**
•	Some fields should be set required and user have to enter proper value. Ex: Day of Campaign

- [x] **Range:**
•	A field that allows only input greater than or equals to the MIN value provided and less than on equals to the MAX value provided.

Form Ex: ICM H2H for Revisit Strategy
Number of houses marked for revisit =< 5
Min = 1
Max = 5

•	The min and max parameters get set by variable/field values for the range.

- [x] **Logical agreement/disagreement between fields:**
•	Value of one field must be greater/less than value of another field.

Form Ex: ICM H2H Household Monitoring
Number of under5 years children living in the house >= Number of under5 years children vaccinated based on recall

- [x] **Use of calculated fields to check for logical agreement:**
•	Summation of several fields must be equal to value of another field.

Form Ex: ICM H2H Household Monitoring
missed children,
Reason 1- team not come,
Reason 2- absent,
Reason 3- NSS,
Reason 4- refusal,

team not come + absent + NSS + refusal = missed children 

- [x] **Calculating among forms:**
•	Ability to call several variables from several forms/days to calculate to another form field. #193 

Form Ex: DC Revisit Compilation Sheet Day 4 H2H
Number of children Remaining Refusal (from Day 1)
+
Number of children Remaining Refusal (from Day 2)
+
Number of children Remaining Refusal (from Day 3)
equal to
Number of children Remaining Refusal (Day 1-3) (in Day 4)

**Comment by xlg8** [comment]
@RaziaMahmodi You and I are supposed to work on the standardized forms for this issue. Please identify the forms we can adapt for implementing this feature so we can work with it. Thanks

**Comment by bnygren** [comment]
Warn user behavior not tested yet. This is important to prevent trapping data entry users on logical check for out of expected range and forcing them to change data to be allowed to save record.

**Comment by xlg8** [comment]
@ToluOlayinka @Iyanuu Please let us know about the "Warn user" Behaviour. We need this done. Thanks

**Comment by xlg8** [comment]
@ToluOlayinka @sundayAdu VERY IMPORTANT TO WORK ON.

**Comment by abahsuccess** [comment]
We have implemented two warning dialogs for the team to choose from.

### 1. This displays in the middle and requires the user to accept the error before they continue
![image](https://user-images.githubusercontent.com/69864014/161393831-11c983b9-5f32-4c67-918e-06ad1f5a3426.png)

### 2. This is a soft warning at the bottom left which disappears after one minute on its own or mouseover.

![image](https://user-images.githubusercontent.com/69864014/161393875-742fc7b1-fbe4-42e5-aef4-3b833e790eef.png)

**Comment by xlg8** [comment]
@abahsuccess @ToluOlayinka @sundayAdu  For the warning trigger, for a warning to test. Regarding the comment from success about UI, we think a persistent popup is needed, but we would use an “allow value” response rather than “x”
