### ISSUE TITLE
Add "Validation" as a form category

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#702]
Add "Validation" in Form Category/ Form Manager. Also add Validation in Users/ Form Access/ Post-Campaign section. 

![Image](https://github.com/user-attachments/assets/99129eaf-032e-40a4-b9eb-11ca7f1f0035)

![Image](https://github.com/user-attachments/assets/fe65a6d3-63e8-47fa-983b-bb8be5420c94)

**Comment by bnygren** [comment]
confirmed
