### ISSUE TITLE
Exported csv files need UTF-8 encoding

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#706]
Based on feedback from data managers, csv files that are exported from APMIS (i.e. through the Campaign Data page and elsewhere) do not use UTF-8 encoding. When viewed in Excel, Excel does not know what encoding to use and this results in garbled text for Dari/Farsi text.
An example can be seen when downloading ICM supervisor monitoring checklist data that includes supervisors names.
This is easy enough to correct, by opening the downloaded csv in a text editor, changing the encoding to 'UTF-8' and saving, then opening in Excel. 
However, to avoid this issue, the downloaded csv files should be encoded with UTF-8 directly.

![Image](https://github.com/user-attachments/assets/7b64202f-2d1d-44a8-98f8-a29fe2fa95fa)

**Comment by bnygren** [comment]
Confirmed that Dari text paste in the web app is viewable in csv's opened with Excel. Also using Windows notepad (FWIW) thinks it is UTF 8 with BOM

**Comment by lbaertlein1** [comment]
Tested a csv download from test.afghanistan-apmis.com and confirmed there is a BOM.
CSVs from the live server "afghanistan-apmis.com" still do not have a BOM.

To test, use: https://validator.w3.org/i18n-checker/check#validate-by-upload+
