### ISSUE TITLE
Region/province/district filters not working for some users

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#708]
If logged in as a 'region-level' user, the province and district filters do not function. EOC users demonstrated it with a region user account, and it looks like a bug.

![image](https://github.com/user-attachments/assets/fb60429f-9b98-47fd-a5cf-d55c8c9bcf63)

**Comment by DevSeg** [comment]
Hi @bnygren, reviewing the underlying cause of this issue we would like for the Label to be updated as an  "Improvement" since the restrictions met by these users was based on the initial filter restriction placed on users by the levels of configuration assignment they have.

**Comment by bnygren** [comment]
Confirmed as working when assigned role of Regional Data Manager and Regional Officer. However, when assigning a role of Regional Observer, I am unable to log into the system at all with the following error message. Changing my role back to another role allows the same user to log back into the system. I am not closing this issue yet because I cannot test as Regional Observer. This is confirmed under two users. see #727 

![Image](https://github.com/user-attachments/assets/9d7f05ed-d0e6-4193-b0f2-cb0da738222f)
