### ISSUE TITLE
Warning popup when reassigning clusters

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#729]
Ability to edit / correct the cluster on header for data. A user may click Reassign Data > change the cluster > Save. This does not save the change to the cluster value. Thus I think there needs to be a popup to warn users they have to click the Update Form Data Unit button to keep their change or lose the cluster change.

To confirm / dismiss, user should click "Ok" and then go back to the form and either reassign the cluster or cancel their edit. 

related: #694

**Comment by RaziaMahmodi** [comment]
the reassign option should not be available for district level forms. 

![Image](https://github.com/user-attachments/assets/4881acbf-8181-4fdc-8612-6b4b157cfebf)
