### ISSUE TITLE
Change test server login background vs. main server

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#73]
### Feature Description

Login background for server
 
### Problem Description

Sometimes users try to log into the wrong URL and both servers appeas

### Proposed Change

Please change the image or color on the login page of the test server to remind users and easily distinguish between the main and test servers while logging in. New image/color TBD

**Comment by xlg8** [comment]
I think we should have the main server login page customized like this

![14C54210-48AA-48C5-9495-317ED66940AE](https://user-images.githubusercontent.com/71328926/152800532-40a4b981-1d2b-474c-9bf7-2f340b5f0669.jpeg)

**Comment by bnygren** [comment]
Agreed it could be improved. A redesign is certainly possible. Let's discuss prioritization.
