### ISSUE TITLE
Discussion item - Form versioning / control

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#735]
To be discussed: For forms that are edited with new fields added, these new fields show up in past campaigns data view as blank, which is confusing and ambiguous about if the field was collected then and when the form was created and so on. Need to either prevent form editing altogether and require a new form for each edit, and/or implement some kind of versioning control. 

This general issue with tracking changes to components also applies to config admin units (e.g., clusters)

**Comment by RaziaMahmodi** [comment]
@bnygren Could we close/delete this issue? as there is already a form versioning issue existing. Please add any content that not already mentioned on issue 748 from this issue.

**Comment by bnygren** [comment]
@RaziaMahmodi sounds good. thanks
