### ISSUE TITLE
Add Region-level user

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#74]
### Situation Description

Create region-level user 
### Feature Description

User has region level viewing and editing privileges.

**Comment by xlg8** [comment]
@sundayAdu Please if this issue has been done, can you kindly implement the region user and the region org unit within the campaign lists? Thanks

**Comment by bnygren** [comment]
Needs https://github.com/xlg8/APMIS-Project/issues/116 to work, otherwise region-level user isn't associated with any region
