### ISSUE TITLE
Cluster API endpoint that returns all clusters

### ISSUE THREAD

**Issue by lbaertlein1** [xlg8/APMIS-Project#740]
### Situation Description
For analytics, we want to be able to retrieve a dataset of all clusters in the database - both active and archived, along with their characteristics. This would be similar to the current 'districts' API endpoint. 
It will be used to monitor data completeness - or the percent of active clusters that have reported in a given SIA.

### Feature Description
The endpoint should function similar to the districts endpoint ("https://afghanistan-apmis.com/sormas-rest/districts/all_/0"), except returning clusters - including cluster code, cluster name, archived status, float status, and metadata like creation date / change date.

**Comment by lbaertlein1** [comment]
"https://afghanistan-apmis.com/sormas-rest/communities/allClusters/0" has now been created as an endpoint.
However, it is not yet correctly pulling the cluster characteristics. Necessary cluster characteristics include: 'archived' (i.e. "Active Status"), "Float Status", cluster name, cluster number, cluster code, cluster uuid, and associated district uuid. Archived and Float Status are not yet correct on the live server.

**Comment by bnygren** [comment]
Confirmed on Test by @lbaertlein1
