### ISSUE TITLE
Validation is checking twice for LQAS lot cluster validation

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#747]
In mobile app, validation is checking twice for LQAS lot cluster number causing preventing user to save and enter data, counting it as duplicate data.

**Comment by DevSeg** [comment]
Hi @RaziaMahmodi  please provide us with additional information on the problems you have encountered while testing this issue out so we can address promptly. Thank you. CC @omoluabidotcom

**Comment by RaziaMahmodi** [comment]
as I tested this, it seems validation is not checking LQAS lot cluster number twice anymore which is fine. But after edit, user is able to submit duplicate rows.

**Comment by RaziaMahmodi** [comment]
@DevSeg 
As I tested this, it seems validation is not checking LQAS lot cluster number twice anymore which is fine. But after edit, user is able to submit duplicate rows.

**Comment by RaziaMahmodi** [comment]
Double validation check do not stop LQAS data entry.
