### ISSUE TITLE
Branching logic in forms

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#75]
### Situation Description

Forms are linear and display static set of input controls. 

### Feature Description

Allow/enable/show additional fields based on the value of a previous field. E.g., if field1 dropdown is "other", enable "specify other" field.

### Possible Alternatives

The JSON logic for skips and branching is embedded in the JSON definition ("DependingOn and DependingOnValues)
Example

{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "Linked scope",
  "properties": {
    "scope": {
      "$id": "#/properties/scope",
      "title": "Project scope",
      "$ref": "#/definitions/Scope"
    }
  },
  "oneOf": [
    {
      "properties": {
        "scope": {
          "properties": {
            "key": {
              "const": "ScopeNational"
            }
          }
        },
        "region": {
          "$ref": "#/definitions/Choice"
        },
        "country": {
          "$ref": "#/definitions/Choice"
        }
      }
    },
    {
      "properties": {
        "scope": {
          "properties": {
            "key": {
              "const": "ScopeRegional"
            }
          }
        },
        "region": {
          "$ref": "#/definitions/Choice"
        },
        "country": {
          "$ref": "#/definitions/NullableChoice"
        }
      }
    },
    {
      "properties": {
        "scope": {
          "properties": {
            "key": {
              "const": "ScopeInternational"
            }
          }
        },
        "region": {
          "$ref": "#/definitions/NullableChoice"
        },
        "country": {
          "$ref": "#/definitions/NullableChoice"
        }
      }
    }
  ],
  "required": [
    "scope",
    "country",
    "region"
  ],
  "definitions": {
    "Choice": {
      "type": "object",
      "properties": {
        "key": {
          "type": "string"
        },
        "text": {
          "type": "string"
        }
      },
      "required": [
        "key",
        "text"
      ]
    },
    "NullableChoice": {
      "type": "object",
      "properties": {
        "key": {
          "type": ["string", "null"]
        },
        "text": {
          "type": ["string", "null"]
        }
      },
      "required": [
        "key",
        "text"
      ]
    },
    "Scope": {
      "type": "object",
      "properties": {
        "key": {
          "type": "string",
          "enum": [
            "ScopeNational",
            "ScopeRegional",
            "ScopeInternational"
          ]
        },
        "text": {
          "type": "string"
        }
      },
      "required": [
        "key",
        "text"
      ]
    }
  }
}
### Additional Information

https://stackoverflow.com/questions/56787812/json-schema-conditionnal-required-depending-on-value

**Comment by xlg8** [comment]
https://pretagteam.com/question/what-are-the-best-ways-to-reference-branches-of-a-json-tree-structure

**Comment by xlg8** [comment]
https://pretagteam.com/question/how-to-automatically-add-a-filter-depending-on-boolean-value-in-json-file
SELECT json_object('id'
   VALUE employee_id,
   'name'
   VALUE first_name || ' ' || last_name,
   'hireDate'
   VALUE hire_date,
   'pay'
   VALUE salary,
   'contactInfo'
   VALUE json_object('mail'
      VALUE email,
      'phone'
      VALUE phone_number) FORMAT JSON)
FROM employees
WHERE salary > 15000;

--The query returns rows such as this(pretty - printed here
      for clarity):

   {
      "id": 101,
      "name": "Neena Kochhar",
      "hireDate": "21-SEP-05",
      "pay": 17000,
      "contactInfo": {
         "mail": "NKOCHHAR",
         "phone": "515.123.4568"
      }
   }

**Comment by bnygren** [comment]
tested

**Comment by bnygren** [comment]
This issue was noted as tested and closed 14 days ago, so no need to review.
