### ISSUE TITLE
Add "Round" as campaign attribute

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#77]
### Situation Description

Round should be added to campaigns as an attribute. round can be selected from a list while creating a campaign on the system.

### Feature Description

Having a round as an attribute of the campaign can be very effective and useful in filtering data and dashboards.

Single-select dropdown

### Possible Alternatives

rounds:
NID, SNID, Case Respond, Mopping-Up

**Comment by bnygren** [comment]
Round is mislabeled as 'CLUSTER' in 1.0.8

**Comment by RaziaMahmodi** [comment]
Need correction on dropdown options. NID, SID, bOPV are not correct.
Dropdown options should be:
NID, SNID, Case Respond, Mopping-Up.

**Comment by xlg8** [comment]
@Iyanuu Please update dropwdown options as specified before we can close it. Thanks
NID, SNID, Case Respond, Mopping-Up.

**Comment by bnygren** [comment]
This wasn't yet designated for review but it is done (value choices updated per above comment), so closing
