### ISSUE TITLE
Add a "Campaign Type" to campaigns

### ISSUE THREAD

**Issue by adekunleakerele** [xlg8/APMIS-Project#8]
From  #2338

Feature Description
To allow additional fields for campaigns that affect the whole campaign, we should add a CampaignType field to campaigns. This should be optional and could initially only contain the "Vaccination" type. Required e.g. because it's necessary to specify a vaccine for NID campaigns, so there could be an additional "Type of vaccine" field that is only visible when Vaccination has been chosen as the CampaignType.

We should have the following levels of campaign categories in addition to what exists:

1. CampaignTypeRound (NID, SNID, Mop-up response, Case response, Outbreak response) - campaign level attribute relates to 77
2. CampaignTypeVaccine (IPV, OPV, nOPV etc.) - not needed
3.  CampaignPhase (Pre-campaign, Intra-campaign, Post-campaign, PTT) - campaign filter for specific activities - 46
4. CampaignModality (House to House-H2H, Mosque to Mosque-M2M, Health Facility to Health Facility-HF2HF, Site to Site- S2S) - form type within intracampaign - not needed form level

**Comment by cassandraSMART** [comment]
can we say this has already been resolved by the use of "dependingOn" in the campaign form definition?

**Comment by xlg8** [comment]
@sundayAdu This has been resolved with the drop down categorical feature. For the depending On values. Please put some examples scripts so we can use to create the cascade foe the categorical drop downs.  And then we can close this issue. What do you think @bnygren Thanks
