### ISSUE TITLE
"--Please Select--" is getting add to campaign as a form

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#87]
### Bug Description

While adding forms and click on "Add Form" then click on "Cancel", "--Please Select--" automatically will be added as a form to campaign.

### Expected Behavior

When "Cancel" will be clicked, it is expected to nothing (no form) will be added to campaign. Also "--Please Select--" is not supposed to be recognized as a selectable value.

### Screenshots

![1](https://user-images.githubusercontent.com/88741672/150406419-ebaf97c6-f4a7-432d-b3b9-62f3af945386.png)
![2](https://user-images.githubusercontent.com/88741672/150406438-af701d60-7593-4016-af2a-cc67ca37fcdd.JPG)

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by Iyanuu** [comment]
@bnygren @RaziaMahmodi A validation check before the save action runs has been added. This checks for any empty row and prevents the user from saving the empty row.

**Comment by xlg8** [comment]
This is still happening. It throws an error when you try to add a new form when a "please select" form is still on active screen. Then when you cancel, it just loops without killing the initial process. We need to look into this. 
![loop-pleaseselect](https://user-images.githubusercontent.com/71328926/155371460-8b847e76-a3b5-4781-ac55-c51dc61fc1f2.JPG)

**Comment by Iyanuu** [comment]
@xlg8 @bnygren @ToluOlayinka @sundayAdu As discussed in the meeting, the two side validation works well but a popup window to indicate an action is needed when a form has not been selected will be added.

**Comment by xlg8** [comment]
@Iyanuu We would need to review an improvement of this with checkboxes in the next phase. Thanks
