### ISSUE TITLE
Cluster dropdown selector to show Cluster ID (name) and number

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#88]
### Feature Description
Concatenate the cluster ID and cluster number in one string to display in the dropdown

e.g., table:
cluster ID      | cluster # | other cluster variables
MyCluster           20             some info
OtherCluster       21             etc.

dropdown shows vlaues:
MyCluster (20)
OtherCluster (21)

### Problem Description

The user may need the cluster number in addition to the cluster ID (name) when selecting cluster from dropdown menu

**Comment by RaziaMahmodi** [comment]
I'll close this issue. The preferred solution is the first task in issue #163 .
