### ISSUE TITLE
Change filename of mobile app to 'APMIS 1.0.x' not SORMAS

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#91]
### Feature Description
Change filename of mobile app to 'APMIS 1.0.x' not SORMAS

**Comment by Iyanuu** [comment]
@ToluOlayinka @bnygren @xlg8 @sundayAdu I believe this is closely linked to issue #76 We are still waiting for the confirmation of system name.

**Comment by bnygren** [comment]
Confirmed filename 'apmis-1.0.11-debug.apk' Version number will need to be updated with release.
