### ISSUE TITLE
Ability to set fields to "Read Only"

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#93]
### Problem Description

Some fields in the form are as descriptions and comment. So it does not need to be displayed in the dataset and to be set just as "Read Only" fields. e.g., the Data Source field should not be in column view

### Proposed Change

Data type: description/ hidden field type. No data to go in this label/info. Won't be stored in db.

### Additional Information

![33](https://user-images.githubusercontent.com/88741672/151203005-74d5181a-9f0b-4e99-8080-dda45b1a788d.JPG)

![22](https://user-images.githubusercontent.com/88741672/151197377-1265550b-8d46-42f2-8a77-192074c5ab41.JPG)

**Comment by ToluOlayinka** [comment]
Identified: DATA SOURCE, FILENAME ... as the columns
Are these all the Columns to expect?

**Comment by xlg8** [comment]
Yes @ToluOlayinka
