### ISSUE TITLE
Add region org unit to all organizational dropdowns on APMIS 

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#95]
The region dropdown is missing from core parts of the system which defaults to province omitting the region dropwdown. This happens for campaign directory and for user creation as well. Also please change Area to Region everywhere on the system. See example in user creation where Area type (Urban/Rural) should be Region Type

![3E1C2BDD-ABCA-461D-BA61-3CF40E9BC866](https://user-images.githubusercontent.com/71328926/152174138-df5f8977-745b-476c-9320-809b7721f8ef.jpeg)

![BA425ED0-A910-4FDE-804A-58BF02786310](https://user-images.githubusercontent.com/71328926/152175192-a79d8847-6730-4b8e-afdc-751bb2ab26cb.jpeg)

**Comment by xlg8** [comment]
https://github.com/xlg8/APMIS-Project/issues/74

**Comment by bnygren** [comment]
believed to be done
