### ISSUE TITLE
User creation page-- Disable Facility, facility cat and facility type/Country

### ISSUE THREAD

**Issue by xlg8** [xlg8/APMIS-Project#96]
On the user creation page, please disable all fields related to facility type, category and facility dropdowns as they are not applicable to APMIS.
![BC33414B-4A4F-4769-BFDF-C98268EE15CA](https://user-images.githubusercontent.com/71328926/152177334-bf5cf294-76cf-43c6-8018-9da484bd2b50.jpeg)

PLEASE ADD region dropdown to user page for creating new users. 
![BA425ED0-A910-4FDE-804A-58BF02786310](https://user-images.githubusercontent.com/71328926/152178392-a3f0d4da-30ae-452c-b9b6-e7ddbc105a81.jpeg)

Please also disable Country from the user creation page. Thanks

**Comment by bnygren** [comment]
updated this issue description to just reflect the fields to drop; Region is added now so removed that description. thanks

**Comment by bnygren** [comment]
confirmed
