### ISSUE TITLE
Logout confirmation / Timer

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#97]
### Situation Description

 When clicking logout, system immediately logs out and loads login page.
Closing the last active tab of APMIS should ideally trigger this behavior as well. 

- [x] Confirmation
- [x] Timer

### Feature Description

Add a popup that states "You will be logged out in XX (30?) seconds and counts down, followed by "you have been logged out". 

The two button options are "Log out" and "Cancel".  **Log out** loads log in screen. **Cancel** returns to existing screen. 

relates to #30

**Comment by RaziaMahmodi** [comment]
I see the timer, OK and Cancel buttons is working. Thanks
