### ISSUE TITLE
Changing "External ID" to "Code No" - settings for Configuration page

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#99]
### Feature Description

- [x] 1- Changing "External ID" to Code No in Configuration page Region and Cluster tabs. 

          in Regions = RCode
          in Clusters = CCode

- [x] 2- Changing "EPID Code" to code No in Configuration page Province and District tabs. 

          in Provinces = PCode
          in Districts = DCode

- [x] 3- Eliminating "External ID" from Provinces and Districts page.

- [x] 4- Eliminating "Country" field from Provinces, New Entry.

- 5- All Code No should be:

- [x] a- Numeric value type (Integer)
- [x] b- Required
- [x] c- Unique

### Additional Information

https://test.afghanistan-apmis.com/sormas-ui/#!configuration

![1](https://user-images.githubusercontent.com/88741672/152410215-2a474cfd-2207-456f-98f1-fa337526145f.JPG)
![2](https://user-images.githubusercontent.com/88741672/152410226-1e70a0f0-7098-4cc9-856d-ebc4e0a9756d.JPG)
![3](https://user-images.githubusercontent.com/88741672/152410233-d37d6d62-0c8b-4a7d-9dce-5b0f18ae092c.JPG)

**Comment by xlg8** [comment]
![image](https://user-images.githubusercontent.com/71328926/158295848-0c5d246a-98bc-467c-9ece-2c1c99aa11f9.png)
I tested this functionality and imported province data. This works now. @RaziaMahmodi can you import now with the correct codes. There is a checkbox for overwriting previous data. I used that to overwrite the previous admin org unit data.

**Comment by ToluOlayinka** [comment]
This is almost done (Left with No5),
We are yet to set Code No to Required field until existing Data has a value to avoid errors

**Comment by RaziaMahmodi** [comment]
@ToluOlayinka I unchecked No 2 because the requested label are not correct (partially done) and No 3 is part of it.
No 4 is not done.
No 5 is not done as you said.

**Comment by RaziaMahmodi** [comment]
@ToluOlayinka These pics clarify No 2,3,4.
![99 Dis](https://user-images.githubusercontent.com/88741672/158433413-78d08922-a30e-4c4e-8d23-509962b85483.JPG)
![99 Pro](https://user-images.githubusercontent.com/88741672/158433417-f75515e8-0639-4f51-91d0-f9f08d168282.JPG)

**Comment by RaziaMahmodi** [comment]
@ToluOlayinka More details for No 5 (part a and c):

RCode = 2 digits Ex: 3, 12
PCode = 2 digits Ex: 1, 8, 21, 31
DCode = 4 digits Ex: 201, 1519, 2708, 3012, 
CCode = 7 digits Ex: 101266, 904009, 1614005, 3001024

When user try to sort the list based on Code No, it won't get sorted correctly:
This pic shows an example on sorting Code No from smallest to largest:

![no 5 exa](https://user-images.githubusercontent.com/88741672/158862130-b85d8e81-b393-4e5f-95d1-5866590e2752.png)

**Comment by ToluOlayinka** [comment]
> @ToluOlayinka More details for No 5 (part a and c):
> 
> RCode = 2 digits Ex: 3, 12 PCode = 2 digits Ex: 1, 8, 21, 31 DCode = 4 digits Ex: 201, 1519, 2708, 3012, CCode = 7 digits Ex: 101266, 904009, 1614005, 3001024
> 
> When user try to sort the list based on Code No, it won't get sorted correctly: This pic shows an example on sorting Code No from smallest to largest:
> 
> ![no 5 exa](https://user-images.githubusercontent.com/88741672/158862130-b85d8e81-b393-4e5f-95d1-5866590e2752.png)

@RaziaMahmodi This has been noted and would be worked on.

**Comment by xlg8** [comment]
@ToluOlayinka But this does not work for 2 digits for Rcode
![54FBC68B-50D2-4829-91C4-1BF0F33B9A59](https://user-images.githubusercontent.com/71328926/161824894-afaa4ccc-2aa8-4f88-9eb5-7b6a4d2b83cc.jpeg)

**Comment by xlg8** [comment]
@ToluOlayinka @sundayAdu Still having this issue in Region
![image](https://user-images.githubusercontent.com/71328926/161996457-b2f5175e-d9a8-4dbf-a863-14f8cada806f.png)
